const { spawn } = require("child_process");
const { chromium } = require("/home/user/passio-app/node_modules/playwright-core");
const GATE_KEY = "passio_gate_v1", GATE_TOKEN = "67a2ba44e8c09efc9e9e9d60690ef7cd1e3069d072231a1834b30ec1fc50390f";
const { onboardedState } = require("/home/user/passio-app/tests/e2e/app-helper.js");
setTimeout(() => { console.error("TIMEOUT"); process.exit(2); }, 120000);
(async () => {
  const srv = spawn("npx", ["http-server", "-p", "8120", "-a", "127.0.0.1", "-c-1", "-s", "."], { cwd: "/home/user/passio-app", stdio: "ignore" });
  await new Promise(r => setTimeout(r, 2500));
  const browser = await chromium.launch();
  const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
  await page.route(/\/rest\/v1\/(posts|stories|events|notifications)\?/, route => route.request().method() === "GET" ? route.fulfill({ status: 200, contentType: "application/json", body: "[]" }) : route.continue());
  await page.routeWebSocket(/\/realtime\/v1\/websocket/, () => {});
  await page.addInitScript(([k, t, st]) => { sessionStorage.setItem(k, t); sessionStorage.setItem("passio_pwa_dismissed", "1"); if (!localStorage.getItem("passio_mvp_state_v1")) localStorage.setItem("passio_mvp_state_v1", JSON.stringify(st)); }, [GATE_KEY, GATE_TOKEN, onboardedState(1)]);
  await page.goto("http://127.0.0.1:8120/index.html");
  await page.waitForFunction(() => { const el = document.getElementById("screen-feed"); return el && el.classList.contains("active"); }, null, { timeout: 30000 });
  await page.waitForFunction(() => typeof openConversation === "function" && typeof _deleteMsgForMe === "function");
  await page.waitForTimeout(1500);
  const r = await page.evaluate(async () => {
    const l = document.getElementById("landing"); if (l) l.classList.remove("active");
    MY_UID = "u_moi"; window._supaReal = true;
    supa = { from: () => ({ insert: () => Promise.resolve({}), upsert: () => Promise.resolve({}), delete: () => ({ eq: () => ({ eq: () => Promise.resolve({}), then: (a) => Promise.resolve({}).then(a) }) }), select: () => ({ eq: () => ({ neq: () => Promise.resolve({ data: [] }), maybeSingle: () => Promise.resolve({ data: null }), eq: () => ({ maybeSingle: () => Promise.resolve({ data: null }) }) }), in: () => Promise.resolve({ data: [] }) }) }), channel: () => ({ on() { return this; }, subscribe() { return this; } }), removeChannel: () => {} };
    window.supaMarkRead = async () => {}; window.supaLoadOtherRead = async () => {};
    window.supaLoadMessages = async () => [{ id: "m1", from: "u_x", text: "Salut", at: Date.now() - 60000 }];
    window.closeModal = window.closeModal || (() => {});
    conversationsState = [{ id: "c_x", userId: "u_x", userName: "Xavier", userEmoji: "🎸", unread: 0, lastAt: Date.now(), messages: [{ id: "m1", from: "u_x", text: "Salut", at: Date.now() - 60000 }] }];
    saveConversationsNow(); goTo("messages"); renderMessages();
    await openConversation("c_x"); await new Promise(r => setTimeout(r, 300));
    _deleteMsgForMe("c_x", "m1");
    const apresSuppr = getConversations().find(c => c.id === "c_x").messages.some(m => m.id === "m1");
    const tomb = JSON.parse(localStorage.getItem("passio_conv_deleted_v1") || "{}");
    closeConversation(); await openConversation("c_x"); await new Promise(r => setTimeout(r, 400));
    const apresReouv = getConversations().find(c => c.id === "c_x").messages.some(m => m.id === "m1");
    const dom = !!document.querySelector('#conv-fullpage [data-msg-id="m1"], #conv-fullpage [data-id="m1"]');
    const domTexte = (document.getElementById("conv-fullpage") || {}).textContent || "";
    return { present_apres_suppression: apresSuppr, tombstone_pose: !!tomb["msg:m1"], present_apres_reouverture: apresReouv, texte_dans_le_fil_apres_reouverture: domTexte.includes("Salut") };
  });
  console.log(JSON.stringify(r));
  await browser.close(); srv.kill(); process.exit(0);
})().catch(e => { console.error("ECHEC", e); process.exit(1); });
