-- ═══════════════════════════════════════════════════════════════════════════
-- DELTA DU RÉFÉRENTIEL DES PASSIONS — 2026-09-09
--
--   180 passions nouvelles · 356 relations
--   (la production en connaissait 1908 ; le référentiel en compte 2088)
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Générateur : node scripts/generer-delta-passions.js --ids <ids-prod.txt>
--
-- ⚠️ CE DELTA NE CRÉE AUCUNE TABLE, AUCUNE POLICY, AUCUNE FONCTION. Il suppose
--    `migration_passions_plat.sql` DÉJÀ appliquée (elle l'est depuis le
--    2026-09-01). S'il devait servir sur une base neuve, appliquer le miroir
--    complet d'abord.
--
-- ⚠️ ADDITIF ET IDEMPOTENT : aucun DROP, aucun DELETE. Une passion ARCHIVÉE
--    par la modération le RESTE (le `case` sur status), et les identifiants
--    historiques gardent `source = 'legacy'`.
--
-- ⚠️ UNE SEULE TRANSACTION : une erreur au milieu n'applique rien du tout.
-- ═══════════════════════════════════════════════════════════════════════════

begin;

insert into public.passions
  (id, label, normalized_label, aliases, status, source, is_broad, popularity, sort_order, emoji, color)
values
  ('langues-catalan', 'Catalan', 'catalan', ARRAY['català','parler catalan']::text[], 'active', 'curated', false, 29, 1707, '🗣️', '#8b5cf6'),
  ('langues-polonais', 'Polonais', 'polonais', ARRAY['polski','parler polonais']::text[], 'active', 'curated', false, 29, 1708, '🗣️', '#8b5cf6'),
  ('langues-tcheque', 'Tchèque', 'tcheque', ARRAY['cestina','parler tchèque']::text[], 'active', 'curated', false, 29, 1709, '🗣️', '#8b5cf6'),
  ('langues-hongrois', 'Hongrois', 'hongrois', ARRAY['magyar','parler hongrois']::text[], 'active', 'curated', false, 29, 1710, '🗣️', '#8b5cf6'),
  ('langues-roumain', 'Roumain', 'roumain', ARRAY['romana','parler roumain']::text[], 'active', 'curated', false, 29, 1711, '🗣️', '#8b5cf6'),
  ('langues-bulgare', 'Bulgare', 'bulgare', ARRAY['parler bulgare']::text[], 'active', 'curated', false, 28, 1712, '🗣️', '#8b5cf6'),
  ('langues-serbo-croate', 'Serbo-croate', 'serbo croate', ARRAY['serbe','croate']::text[], 'active', 'curated', false, 28, 1713, '🗣️', '#8b5cf6'),
  ('langues-ukrainien', 'Ukrainien', 'ukrainien', ARRAY['parler ukrainien','ukrainskа']::text[], 'active', 'curated', false, 28, 1714, '🗣️', '#8b5cf6'),
  ('langues-danois', 'Danois', 'danois', ARRAY['dansk','parler danois']::text[], 'active', 'curated', false, 28, 1715, '🗣️', '#8b5cf6'),
  ('langues-norvegien', 'Norvégien', 'norvegien', ARRAY['norsk','parler norvégien']::text[], 'active', 'curated', false, 28, 1716, '🗣️', '#8b5cf6'),
  ('langues-finnois', 'Finnois', 'finnois', ARRAY['suomi','parler finnois']::text[], 'active', 'curated', false, 28, 1717, '🗣️', '#8b5cf6'),
  ('langues-islandais', 'Islandais', 'islandais', ARRAY['parler islandais']::text[], 'active', 'curated', false, 28, 1718, '🗣️', '#8b5cf6'),
  ('langues-hebreu', 'Hébreu', 'hebreu', ARRAY['ivrit','hébreu moderne']::text[], 'active', 'curated', false, 28, 1719, '🗣️', '#8b5cf6'),
  ('langues-persan', 'Persan', 'persan', ARRAY['farsi','parler persan']::text[], 'active', 'curated', false, 28, 1720, '🗣️', '#8b5cf6'),
  ('langues-vietnamien', 'Vietnamien', 'vietnamien', ARRAY['parler vietnamien','tieng viet']::text[], 'active', 'curated', false, 28, 1721, '🗣️', '#8b5cf6'),
  ('langues-thai', 'Thaïlandais', 'thailandais', ARRAY['parler thaï','langue de thaïlande']::text[], 'active', 'curated', false, 27, 1722, '🗣️', '#8b5cf6'),
  ('langues-indonesien', 'Indonésien', 'indonesien', ARRAY['bahasa indonesia','malais']::text[], 'active', 'curated', false, 27, 1723, '🗣️', '#8b5cf6'),
  ('langues-swahili', 'Swahili', 'swahili', ARRAY['kiswahili','parler swahili']::text[], 'active', 'curated', false, 27, 1724, '🗣️', '#8b5cf6'),
  ('langues-wolof', 'Wolof', 'wolof', ARRAY['parler wolof']::text[], 'active', 'curated', false, 27, 1725, '🗣️', '#8b5cf6'),
  ('langues-amharique', 'Amharique', 'amharique', ARRAY['parler amharique']::text[], 'active', 'curated', false, 27, 1726, '🗣️', '#8b5cf6'),
  ('langues-bengali', 'Bengali', 'bengali', ARRAY['bangla','parler bengali']::text[], 'active', 'curated', false, 27, 1727, '🗣️', '#8b5cf6'),
  ('langues-ourdou', 'Ourdou', 'ourdou', ARRAY['urdu','parler ourdou']::text[], 'active', 'curated', false, 27, 1728, '🗣️', '#8b5cf6'),
  ('langues-tamoul', 'Tamoul', 'tamoul', ARRAY['parler tamoul']::text[], 'active', 'curated', false, 27, 1729, '🗣️', '#8b5cf6'),
  ('langues-punjabi', 'Pendjabi', 'pendjabi', ARRAY['punjabi','parler pendjabi']::text[], 'active', 'curated', false, 27, 1730, '🗣️', '#8b5cf6'),
  ('langues-tagalog', 'Tagalog', 'tagalog', ARRAY['filipino','parler tagalog']::text[], 'active', 'curated', false, 27, 1731, '🗣️', '#8b5cf6'),
  ('langues-berbere', 'Berbère', 'berbere', ARRAY['amazigh','tamazight','kabyle']::text[], 'active', 'curated', false, 26, 1732, '🗣️', '#8b5cf6'),
  ('langues-galicien', 'Galicien', 'galicien', ARRAY['galego']::text[], 'active', 'curated', false, 26, 1733, '🗣️', '#8b5cf6'),
  ('langues-gallois', 'Gallois', 'gallois', ARRAY['cymraeg','langue du pays de galles']::text[], 'active', 'curated', false, 26, 1734, '🗣️', '#8b5cf6'),
  ('langues-irlandais', 'Irlandais', 'irlandais', ARRAY['gaeilge','gaélique irlandais']::text[], 'active', 'curated', false, 26, 1735, '🗣️', '#8b5cf6'),
  ('langues-ecossais-gaelique', 'Gaélique écossais', 'gaelique ecossais', ARRAY['gàidhlig']::text[], 'active', 'curated', false, 26, 1736, '🗣️', '#8b5cf6'),
  ('langues-picard', 'Picard', 'picard', ARRAY['ch''ti','chtimi']::text[], 'active', 'curated', false, 26, 1737, '🗣️', '#8b5cf6'),
  ('langues-normand', 'Normand', 'normand', ARRAY['langue normande']::text[], 'active', 'curated', false, 26, 1738, '🗣️', '#8b5cf6'),
  ('langues-gascon', 'Gascon', 'gascon', ARRAY['langue gasconne']::text[], 'active', 'curated', false, 26, 1739, '🗣️', '#8b5cf6'),
  ('langues-savoyard', 'Savoyard', 'savoyard', ARRAY['arpitan','franco-provençal']::text[], 'active', 'curated', false, 26, 1740, '🗣️', '#8b5cf6'),
  ('langues-ch-suisse-allemand', 'Suisse allemand', 'suisse allemand', ARRAY['schwyzerdütsch','alémanique']::text[], 'active', 'curated', false, 26, 1741, '🗣️', '#8b5cf6'),
  ('langues-luxembourgeois', 'Luxembourgeois', 'luxembourgeois', ARRAY['lëtzebuergesch']::text[], 'active', 'curated', false, 25, 1742, '🗣️', '#8b5cf6'),
  ('langues-quebecois', 'Français québécois', 'francais quebecois', ARRAY['joual','accent québécois']::text[], 'active', 'curated', false, 25, 1743, '🗣️', '#8b5cf6'),
  ('langues-signes-internationale', 'Langue des signes internationale', 'langue des signes internationale', ARRAY['lsi','signes internationaux']::text[], 'active', 'curated', false, 25, 1744, '🗣️', '#8b5cf6'),
  ('langues-braille', 'Braille', 'braille', ARRAY['lecture tactile','écriture braille']::text[], 'active', 'curated', false, 25, 1745, '🗣️', '#8b5cf6'),
  ('langues-calligraphie-arabe', 'Calligraphie arabe', 'calligraphie arabe', ARRAY['khatt','écriture arabe']::text[], 'active', 'curated', false, 25, 1746, '🗣️', '#8b5cf6'),
  ('langues-ecriture-japonaise', 'Écriture japonaise', 'ecriture japonaise', ARRAY['katakana','shodo']::text[], 'active', 'curated', false, 25, 1747, '🗣️', '#8b5cf6'),
  ('langues-hieroglyphes', 'Hiéroglyphes', 'hieroglyphes', ARRAY['égyptien ancien','écriture égyptienne']::text[], 'active', 'curated', false, 25, 1748, '🗣️', '#8b5cf6'),
  ('langues-sanskrit', 'Sanskrit', 'sanskrit', ARRAY['langue védique']::text[], 'active', 'curated', false, 25, 1749, '🗣️', '#8b5cf6'),
  ('langues-gotique', 'Langues anciennes', 'langues anciennes', ARRAY['vieux norrois','langues mortes']::text[], 'active', 'curated', false, 25, 1750, '🗣️', '#8b5cf6'),
  ('langues-vocabulaire', 'Enrichir son vocabulaire', 'enrichir son vocabulaire', ARRAY['mots rares','lexique']::text[], 'active', 'curated', false, 25, 1751, '🗣️', '#8b5cf6'),
  ('langues-expressions', 'Expressions et idiomes', 'expressions et idiomes', ARRAY['proverbes','tournures']::text[], 'active', 'curated', false, 24, 1752, '🗣️', '#8b5cf6'),
  ('langues-faux-amis', 'Faux-amis', 'faux amis', ARRAY['pièges de traduction']::text[], 'active', 'curated', false, 24, 1753, '🗣️', '#8b5cf6'),
  ('langues-conjugaison', 'Conjugaison', 'conjugaison', ARRAY['verbes','temps verbaux']::text[], 'active', 'curated', false, 24, 1754, '🗣️', '#8b5cf6'),
  ('langues-dictee', 'Dictée', 'dictee', ARRAY['dictées','concours d''orthographe']::text[], 'active', 'curated', false, 24, 1755, '🗣️', '#8b5cf6'),
  ('langues-correspondance', 'Correspondance internationale', 'correspondance internationale', ARRAY['pen pal','correspondant étranger']::text[], 'active', 'curated', false, 24, 1756, '🗣️', '#8b5cf6'),
  ('langues-preparation-toeic', 'Tests de langue', 'tests de langue', ARRAY['toeic','toefl','ielts']::text[], 'active', 'curated', false, 24, 1757, '🗣️', '#8b5cf6'),
  ('langues-langue-maternelle', 'Transmettre sa langue', 'transmettre sa langue', ARRAY['bilinguisme','langue d''origine']::text[], 'active', 'curated', false, 24, 1758, '🗣️', '#8b5cf6'),
  ('langues-argot', 'Argot et parlers', 'argot et parlers', ARRAY['verlan','slang']::text[], 'active', 'curated', false, 24, 1759, '🗣️', '#8b5cf6'),
  ('langues-toponymie', 'Toponymie', 'toponymie', ARRAY['noms de lieux','origine des noms']::text[], 'active', 'curated', false, 24, 1760, '🗣️', '#8b5cf6'),
  ('langues-onomastique', 'Noms de famille', 'noms de famille', ARRAY['onomastique','patronymes']::text[], 'active', 'curated', false, 24, 1761, '🗣️', '#8b5cf6'),
  ('apprentissage-fiches', 'Fiches de révision', 'fiches de revision', ARRAY['flashcards','cartes mémoire']::text[], 'active', 'curated', false, 23, 1762, '🎓', '#7c3aed'),
  ('apprentissage-mind-mapping', 'Cartes mentales', 'cartes mentales', ARRAY['mind map','schéma heuristique']::text[], 'active', 'curated', false, 23, 1763, '🎓', '#7c3aed'),
  ('apprentissage-concentration', 'Se concentrer', 'se concentrer', ARRAY['focus','deep work']::text[], 'active', 'curated', false, 23, 1764, '🎓', '#7c3aed'),
  ('apprentissage-pomodoro', 'Gestion du temps d''étude', 'gestion du temps d etude', ARRAY['pomodoro','planning de révision']::text[], 'active', 'curated', false, 23, 1765, '🎓', '#7c3aed'),
  ('apprentissage-procrastination', 'Vaincre la procrastination', 'vaincre la procrastination', ARRAY['procrastination','se mettre au travail']::text[], 'active', 'curated', false, 23, 1766, '🎓', '#7c3aed'),
  ('apprentissage-oral', 'Passer un oral', 'passer un oral', ARRAY['épreuve orale','soutenance']::text[], 'active', 'curated', false, 23, 1767, '🎓', '#7c3aed'),
  ('apprentissage-memoire-these', 'Mémoire et thèse', 'memoire et these', ARRAY['rédaction académique','doctorat']::text[], 'active', 'curated', false, 23, 1768, '🎓', '#7c3aed'),
  ('apprentissage-recherche', 'Recherche académique', 'recherche academique', ARRAY['chercheur','laboratoire']::text[], 'active', 'curated', false, 23, 1769, '🎓', '#7c3aed'),
  ('apprentissage-methodologie-sources', 'Vérifier ses sources', 'verifier ses sources', ARRAY['sourcer une information','recoupement']::text[], 'active', 'curated', false, 23, 1770, '🎓', '#7c3aed'),
  ('apprentissage-apprendre-adulte', 'Apprendre à l''âge adulte', 'apprendre a l age adulte', ARRAY['reprise d''études','formation adulte']::text[], 'active', 'curated', false, 23, 1771, '🎓', '#7c3aed'),
  ('apprentissage-alternance', 'Alternance', 'alternance', ARRAY['apprentissage en entreprise','contrat pro']::text[], 'active', 'curated', false, 22, 1772, '🎓', '#7c3aed'),
  ('apprentissage-orientation', 'Orientation scolaire', 'orientation scolaire', ARRAY['choisir sa voie','parcoursup']::text[], 'active', 'curated', false, 22, 1773, '🎓', '#7c3aed'),
  ('apprentissage-erasmus', 'Études à l''étranger', 'etudes a l etranger', ARRAY['erasmus','échange universitaire']::text[], 'active', 'curated', false, 22, 1774, '🎓', '#7c3aed'),
  ('apprentissage-tutorat', 'Tutorat', 'tutorat', ARRAY['tuteur','accompagner un élève']::text[], 'active', 'curated', false, 22, 1775, '🎓', '#7c3aed'),
  ('apprentissage-groupe-etude', 'Groupe d''étude', 'groupe d etude', ARRAY['réviser à plusieurs','study group']::text[], 'active', 'curated', false, 22, 1776, '🎓', '#7c3aed'),
  ('apprentissage-classe-inversee', 'Pédagogie active', 'pedagogie active', ARRAY['classe inversée','apprendre en faisant']::text[], 'active', 'curated', false, 22, 1777, '🎓', '#7c3aed'),
  ('apprentissage-serious-game', 'Apprendre par le jeu', 'apprendre par le jeu', ARRAY['serious game','ludopédagogie']::text[], 'active', 'curated', false, 22, 1778, '🎓', '#7c3aed'),
  ('apprentissage-carnet', 'Carnet d''apprentissage', 'carnet d apprentissage', ARRAY['learning log','carnet de progression']::text[], 'active', 'curated', false, 22, 1779, '🎓', '#7c3aed'),
  ('apprentissage-veille', 'Veille', 'veille', ARRAY['curation','se tenir informé']::text[], 'active', 'curated', false, 22, 1780, '🎓', '#7c3aed'),
  ('apprentissage-bibliotheque-perso', 'Bibliothèque personnelle', 'bibliotheque personnelle', ARRAY['ranger ses livres','base de connaissances']::text[], 'active', 'curated', false, 22, 1781, '🎓', '#7c3aed'),
  ('apprentissage-podcast-savoir', 'Podcasts de savoir', 'podcasts de savoir', ARRAY['podcasts éducatifs','apprendre en écoutant']::text[], 'active', 'curated', false, 21, 1782, '🎓', '#7c3aed'),
  ('apprentissage-quiz', 'Quiz et culture G', 'quiz et culture g', ARRAY['questions pour un champion','trivia']::text[], 'active', 'curated', false, 21, 1783, '🎓', '#7c3aed'),
  ('apprentissage-competition-savoir', 'Concours de connaissances', 'concours de connaissances', ARRAY['olympiades','championnat de mémoire']::text[], 'active', 'curated', false, 21, 1784, '🎓', '#7c3aed'),
  ('apprentissage-transmission', 'Transmettre un savoir', 'transmettre un savoir', ARRAY['partager ses compétences','atelier découverte']::text[], 'active', 'curated', false, 21, 1785, '🎓', '#7c3aed'),
  ('apprentissage-benevolat-education', 'Bénévolat éducatif', 'benevolat educatif', ARRAY['accompagnement scolaire','aide aux apprentissages']::text[], 'active', 'curated', false, 21, 1786, '🎓', '#7c3aed'),
  ('philosophie-antique', 'Philosophie antique', 'philosophie antique', ARRAY['socrate','platon','aristote']::text[], 'active', 'curated', false, 21, 1787, '🕊️', '#a78bfa'),
  ('philosophie-epicurisme', 'Épicurisme', 'epicurisme', ARRAY['épicure','hédonisme']::text[], 'active', 'curated', false, 21, 1788, '🕊️', '#a78bfa'),
  ('philosophie-existentialisme', 'Existentialisme', 'existentialisme', ARRAY['sartre','camus']::text[], 'active', 'curated', false, 21, 1789, '🕊️', '#a78bfa'),
  ('philosophie-phenomenologie', 'Phénoménologie', 'phenomenologie', ARRAY['husserl','merleau-ponty']::text[], 'active', 'curated', false, 21, 1790, '🕊️', '#a78bfa'),
  ('philosophie-politique', 'Philosophie politique', 'philosophie politique', ARRAY['contrat social','théorie politique']::text[], 'active', 'curated', false, 21, 1791, '🕊️', '#a78bfa'),
  ('philosophie-esthetique', 'Esthétique', 'esthetique', ARRAY['philosophie de l''art','beau']::text[], 'active', 'curated', false, 20, 1792, '🕊️', '#a78bfa'),
  ('philosophie-logique', 'Logique', 'logique', ARRAY['raisonnement','syllogisme']::text[], 'active', 'curated', false, 20, 1793, '🕊️', '#a78bfa'),
  ('philosophie-metaphysique', 'Métaphysique', 'metaphysique', ARRAY['ontologie','être']::text[], 'active', 'curated', false, 20, 1794, '🕊️', '#a78bfa'),
  ('philosophie-orientale', 'Philosophies orientales', 'philosophies orientales', ARRAY['taoïsme','confucianisme','bouddhisme philosophique']::text[], 'active', 'curated', false, 20, 1795, '🕊️', '#a78bfa'),
  ('philosophie-cafe-philo', 'Café philo', 'cafe philo', ARRAY['atelier philo','discussion philosophique']::text[], 'active', 'curated', false, 20, 1796, '🕊️', '#a78bfa'),
  ('philosophie-sagesse', 'Sagesse et art de vivre', 'sagesse et art de vivre', ARRAY['philosophie pratique','vie bonne']::text[], 'active', 'curated', false, 20, 1797, '🕊️', '#a78bfa'),
  ('philosophie-psychanalyse', 'Psychanalyse', 'psychanalyse', ARRAY['freud','lacan']::text[], 'active', 'curated', false, 20, 1798, '🕊️', '#a78bfa'),
  ('philosophie-neurosciences-esprit', 'Sciences cognitives', 'sciences cognitives', ARRAY['cognition','fonctionnement du cerveau']::text[], 'active', 'curated', false, 20, 1799, '🕊️', '#a78bfa'),
  ('philosophie-utopies', 'Utopies', 'utopies', ARRAY['pensée utopique','imaginer un autre monde']::text[], 'active', 'curated', false, 20, 1800, '🕊️', '#a78bfa'),
  ('philosophie-futurologie', 'Prospective', 'prospective', ARRAY['futurologie','penser le futur']::text[], 'active', 'curated', false, 20, 1801, '🕊️', '#a78bfa'),
  ('philosophie-ecologie-pensee', 'Pensée écologique', 'pensee ecologique', ARRAY['écologie politique','philosophie de la nature']::text[], 'active', 'curated', false, 19, 1802, '🕊️', '#a78bfa'),
  ('philosophie-feminisme-idees', 'Pensée féministe', 'pensee feministe', ARRAY['théorie féministe','études de genre']::text[], 'active', 'curated', false, 19, 1803, '🕊️', '#a78bfa'),
  ('philosophie-droit-idees', 'Philosophie du droit', 'philosophie du droit', ARRAY['théorie du droit','idée de justice']::text[], 'active', 'curated', false, 19, 1804, '🕊️', '#a78bfa'),
  ('philosophie-economie-idees', 'Histoire des idées économiques', 'histoire des idees economiques', ARRAY['pensée économique','doctrines']::text[], 'active', 'curated', false, 19, 1805, '🕊️', '#a78bfa'),
  ('philosophie-lecture-classiques', 'Lire les classiques', 'lire les classiques', ARRAY['grands textes','textes fondateurs']::text[], 'active', 'curated', false, 19, 1806, '🕊️', '#a78bfa'),
  ('eloquence', 'Éloquence', 'eloquence', ARRAY['prise de parole','parler en public','rhétorique']::text[], 'active', 'curated', true, 1219, 1807, '🎙️', '#8b5cf6'),
  ('eloquence-debat', 'Débat', 'debat', ARRAY['débattre','joute oratoire']::text[], 'active', 'curated', false, 19, 1808, '🎙️', '#8b5cf6'),
  ('eloquence-argumentation', 'Argumentation', 'argumentation', ARRAY['argumenter','construire un raisonnement']::text[], 'active', 'curated', false, 19, 1809, '🎙️', '#8b5cf6'),
  ('eloquence-improvisation-oratoire', 'Improvisation oratoire', 'improvisation oratoire', ARRAY['impro oratoire','parler sans notes']::text[], 'active', 'curated', false, 19, 1810, '🎙️', '#8b5cf6'),
  ('eloquence-trac', 'Vaincre le trac', 'vaincre le trac', ARRAY['trac','peur de parler']::text[], 'active', 'curated', false, 19, 1811, '🎙️', '#8b5cf6'),
  ('eloquence-storytelling', 'Storytelling', 'storytelling', ARRAY['raconter une histoire','narration orale']::text[], 'active', 'curated', false, 18, 1812, '🎙️', '#8b5cf6'),
  ('eloquence-pitch', 'Pitcher une idée', 'pitcher une idee', ARRAY['pitch','convaincre en une minute']::text[], 'active', 'curated', false, 18, 1813, '🎙️', '#8b5cf6'),
  ('eloquence-voix', 'Travail de la voix', 'travail de la voix', ARRAY['pose de voix','diction']::text[], 'active', 'curated', false, 18, 1814, '🎙️', '#8b5cf6'),
  ('eloquence-mediation', 'Médiation', 'mediation', ARRAY['résolution de conflits','médiateur']::text[], 'active', 'curated', false, 18, 1815, '🎙️', '#8b5cf6'),
  ('eloquence-animation-reunion', 'Animer une réunion', 'animer une reunion', ARRAY['facilitation','conduite de réunion']::text[], 'active', 'curated', false, 18, 1816, '🎙️', '#8b5cf6'),
  ('eloquence-toastmasters', 'Clubs d''orateurs', 'clubs d orateurs', ARRAY['toastmasters','club de parole']::text[], 'active', 'curated', false, 18, 1817, '🎙️', '#8b5cf6'),
  ('eloquence-plaidoirie', 'Plaidoirie', 'plaidoirie', ARRAY['concours de plaidoirie','barreau']::text[], 'active', 'curated', false, 18, 1818, '🎙️', '#8b5cf6'),
  ('eloquence-ecoute', 'Écoute active', 'ecoute active', ARRAY['savoir écouter','reformulation']::text[], 'active', 'curated', false, 18, 1819, '🎙️', '#8b5cf6'),
  ('eloquence-communication-non-violente', 'Communication non violente', 'communication non violente', ARRAY['cnv','parler sans blesser']::text[], 'active', 'curated', false, 18, 1820, '🎙️', '#8b5cf6'),
  ('genealogie-etat-civil', 'État civil ancien', 'etat civil ancien', ARRAY['registres paroissiaux','actes de naissance']::text[], 'active', 'curated', false, 18, 1821, '🏛️', '#6d28d9'),
  ('genealogie-adn', 'Généalogie génétique', 'genealogie genetique', ARRAY['test adn','cousins génétiques']::text[], 'active', 'curated', false, 17, 1822, '🏛️', '#6d28d9'),
  ('genealogie-histoire-familiale', 'Histoire familiale', 'histoire familiale', ARRAY['récit de famille','mémoire des anciens']::text[], 'active', 'curated', false, 17, 1823, '🏛️', '#6d28d9'),
  ('genealogie-photos-anciennes', 'Photos de famille anciennes', 'photos de famille anciennes', ARRAY['restaurer des photos','identifier des clichés']::text[], 'active', 'curated', false, 17, 1824, '🏛️', '#6d28d9'),
  ('genealogie-migrations', 'Histoire des migrations', 'histoire des migrations', ARRAY['parcours migratoire','immigration familiale']::text[], 'active', 'curated', false, 17, 1825, '🏛️', '#6d28d9'),
  ('genealogie-noms-lieux', 'Origines géographiques', 'origines geographiques', ARRAY['village d''origine','terroir familial']::text[], 'active', 'curated', false, 17, 1826, '🏛️', '#6d28d9'),
  ('genealogie-recits-oraux', 'Recueillir des témoignages', 'recueillir des temoignages', ARRAY['histoire orale','interviewer ses aînés']::text[], 'active', 'curated', false, 17, 1827, '🏛️', '#6d28d9'),
  ('genealogie-numerisation', 'Numériser ses archives', 'numeriser ses archives', ARRAY['scanner des documents','préserver la mémoire']::text[], 'active', 'curated', false, 17, 1828, '🏛️', '#6d28d9'),
  ('geographie-demographie', 'Démographie', 'demographie', ARRAY['population','statistiques de population']::text[], 'active', 'curated', false, 17, 1829, '🔬', '#7c3aed'),
  ('geographie-urbanisme-savoir', 'Urbanisme', 'urbanisme', ARRAY['aménagement du territoire','ville']::text[], 'active', 'curated', false, 17, 1830, '🔬', '#7c3aed'),
  ('geographie-toponymes', 'Drapeaux et pays', 'drapeaux et pays', ARRAY['vexillologie','drapeaux du monde']::text[], 'active', 'curated', false, 17, 1831, '🔬', '#7c3aed'),
  ('geographie-globes', 'Globes et atlas', 'globes et atlas', ARRAY['atlas anciens','mappemonde']::text[], 'active', 'curated', false, 16, 1832, '🔬', '#7c3aed'),
  ('geographie-exploration', 'Grandes explorations', 'grandes explorations', ARRAY['explorateurs','découvertes géographiques']::text[], 'active', 'curated', false, 16, 1833, '🔬', '#7c3aed'),
  ('geographie-geocaching-savoir', 'Géolocalisation', 'geolocalisation', ARRAY['coordonnées','gps loisir']::text[], 'active', 'curated', false, 16, 1834, '🔬', '#7c3aed'),
  ('geographie-hydrographie', 'Fleuves et océans', 'fleuves et oceans', ARRAY['hydrographie','bassins versants']::text[], 'active', 'curated', false, 16, 1835, '🔬', '#7c3aed'),
  ('geographie-montagnes', 'Reliefs et montagnes', 'reliefs et montagnes', ARRAY['massifs','sommets du monde']::text[], 'active', 'curated', false, 16, 1836, '🔬', '#7c3aed'),
  ('documentation', 'Documentation', 'documentation', ARRAY['documenter','classer','archiver']::text[], 'active', 'curated', true, 216, 1837, '📚', '#7c3aed'),
  ('documentation-bibliotheconomie', 'Bibliothéconomie', 'bibliotheconomie', ARRAY['bibliothécaire','classement des livres']::text[], 'active', 'curated', false, 16, 1838, '📚', '#7c3aed'),
  ('documentation-wikipedia', 'Contribuer à Wikipédia', 'contribuer a wikipedia', ARRAY['wikipédien','contribution encyclopédique']::text[], 'active', 'curated', false, 16, 1839, '📚', '#7c3aed'),
  ('documentation-open-data', 'Données ouvertes', 'donnees ouvertes', ARRAY['open data','jeux de données publics']::text[], 'active', 'curated', false, 16, 1840, '📚', '#7c3aed'),
  ('documentation-veille-juridique', 'Droit au quotidien', 'droit au quotidien', ARRAY['connaître ses droits','juridique pratique']::text[], 'active', 'curated', false, 16, 1841, '📚', '#7c3aed'),
  ('documentation-administratif', 'Démarches administratives', 'demarches administratives', ARRAY['paperasse','administration']::text[], 'active', 'curated', false, 15, 1842, '📚', '#7c3aed'),
  ('documentation-securite-numerique', 'Hygiène numérique', 'hygiene numerique', ARRAY['protéger ses données','vie privée en ligne']::text[], 'active', 'curated', false, 15, 1843, '📚', '#7c3aed'),
  ('documentation-reparation-savoir', 'Savoir réparer', 'savoir reparer', ARRAY['réparabilité','autonomie technique']::text[], 'active', 'curated', false, 15, 1844, '📚', '#7c3aed'),
  ('documentation-encyclopedisme', 'Curiosité encyclopédique', 'curiosite encyclopedique', ARRAY['tout savoir','culture encyclopédique']::text[], 'active', 'curated', false, 15, 1845, '📚', '#7c3aed'),
  ('collections-etiquettes-biere', 'Étiquettes de bière', 'etiquettes de biere', ARRAY['tégestophilie','sous-bocks']::text[], 'active', 'curated', false, 15, 1846, '🗃️', '#a78bfa'),
  ('collections-des', 'Dés et accessoires de jeu', 'des et accessoires de jeu', ARRAY['collection de dés','dés à jouer']::text[], 'active', 'curated', false, 15, 1847, '🗃️', '#a78bfa'),
  ('collections-stylos', 'Stylos et plumes', 'stylos et plumes', ARRAY['stylo plume','instruments d''écriture']::text[], 'active', 'curated', false, 15, 1848, '🗃️', '#a78bfa'),
  ('collections-cartes-a-jouer', 'Cartes à jouer', 'cartes a jouer', ARRAY['jeux de cartes anciens','tarots anciens']::text[], 'active', 'curated', false, 15, 1849, '🗃️', '#a78bfa'),
  ('collections-boites', 'Boîtes et coffrets', 'boites et coffrets', ARRAY['boîtes anciennes','objets de rangement']::text[], 'active', 'curated', false, 15, 1850, '🗃️', '#a78bfa'),
  ('collections-cles', 'Clés et serrures', 'cles et serrures', ARRAY['serrurerie ancienne','clés anciennes']::text[], 'active', 'curated', false, 15, 1851, '🗃️', '#a78bfa'),
  ('collections-outils-anciens', 'Outils anciens', 'outils anciens', ARRAY['outillage d''autrefois','outils de métier']::text[], 'active', 'curated', false, 14, 1852, '🗃️', '#a78bfa'),
  ('collections-instruments-scientifiques', 'Instruments scientifiques', 'instruments scientifiques', ARRAY['microscopes anciens','instruments de mesure']::text[], 'active', 'curated', false, 14, 1853, '🗃️', '#a78bfa'),
  ('collections-globes-terrestres', 'Objets de marine', 'objets de marine', ARRAY['instruments de navigation','marine ancienne']::text[], 'active', 'curated', false, 14, 1854, '🗃️', '#a78bfa'),
  ('collections-textile-ancien', 'Textiles anciens', 'textiles anciens', ARRAY['dentelles','broderies anciennes']::text[], 'active', 'curated', false, 14, 1855, '🗃️', '#a78bfa'),
  ('collections-bijoux-anciens', 'Bijoux anciens', 'bijoux anciens', ARRAY['bijouterie ancienne','parures']::text[], 'active', 'curated', false, 14, 1856, '🗃️', '#a78bfa'),
  ('collections-disques-45', 'Singles et 45 tours', 'singles et 45 tours', ARRAY['45 tours','singles vinyles']::text[], 'active', 'curated', false, 14, 1857, '🗃️', '#a78bfa'),
  ('collections-partitions', 'Partitions anciennes', 'partitions anciennes', ARRAY['recueils de musique','partitions de collection']::text[], 'active', 'curated', false, 14, 1858, '🗃️', '#a78bfa'),
  ('collections-journaux', 'Presse ancienne', 'presse ancienne', ARRAY['vieux journaux','unes historiques']::text[], 'active', 'curated', false, 14, 1859, '🗃️', '#a78bfa'),
  ('collections-fanzines', 'Fanzines', 'fanzines', ARRAY['presse alternative','zines']::text[], 'active', 'curated', false, 14, 1860, '🗃️', '#a78bfa'),
  ('collections-billets', 'Billets de banque', 'billets de banque', ARRAY['billets anciens','notaphilie']::text[], 'active', 'curated', false, 14, 1861, '🗃️', '#a78bfa'),
  ('collections-medailles', 'Médailles et décorations', 'medailles et decorations', ARRAY['phaléristique','insignes']::text[], 'active', 'curated', false, 13, 1862, '🗃️', '#a78bfa'),
  ('collections-badges', 'Badges et pin''s', 'badges et pin s', ARRAY['pins','épinglettes']::text[], 'active', 'curated', false, 13, 1863, '🗃️', '#a78bfa'),
  ('collections-emballages', 'Packagings et réclames', 'packagings et reclames', ARRAY['publicités anciennes','boîtes vintage']::text[], 'active', 'curated', false, 13, 1864, '🗃️', '#a78bfa'),
  ('collections-vaisselle-emaillee', 'Objets émaillés', 'objets emailles', ARRAY['plaques émaillées','tôle émaillée']::text[], 'active', 'curated', false, 13, 1865, '🗃️', '#a78bfa'),
  ('collections-horlogerie-ancienne', 'Horloges anciennes', 'horloges anciennes', ARRAY['pendules','mécanismes horlogers']::text[], 'active', 'curated', false, 13, 1866, '🗃️', '#a78bfa'),
  ('collections-radios-anciennes', 'Radios et TSF', 'radios et tsf', ARRAY['postes de radio anciens','tsf']::text[], 'active', 'curated', false, 13, 1867, '🗃️', '#a78bfa'),
  ('collections-telephones', 'Téléphones anciens', 'telephones anciens', ARRAY['téléphonie vintage','cadran']::text[], 'active', 'curated', false, 13, 1868, '🗃️', '#a78bfa'),
  ('collections-machines-a-ecrire', 'Machines à écrire', 'machines a ecrire', ARRAY['dactylographie ancienne','typewriter']::text[], 'active', 'curated', false, 13, 1869, '🗃️', '#a78bfa'),
  ('collections-calculatrices', 'Calculatrices et règles', 'calculatrices et regles', ARRAY['règle à calcul','calculatrices anciennes']::text[], 'active', 'curated', false, 13, 1870, '🗃️', '#a78bfa'),
  ('collections-jeux-anciens', 'Jeux de société anciens', 'jeux de societe anciens', ARRAY['jeux vintage','plateaux anciens']::text[], 'active', 'curated', false, 13, 1871, '🗃️', '#a78bfa'),
  ('collections-poupees', 'Poupées de collection', 'poupees de collection', ARRAY['poupées anciennes','poupées de porcelaine']::text[], 'active', 'curated', false, 12, 1872, '🗃️', '#a78bfa'),
  ('collections-peluches', 'Peluches de collection', 'peluches de collection', ARRAY['ours en peluche','nounours anciens']::text[], 'active', 'curated', false, 12, 1873, '🗃️', '#a78bfa'),
  ('collections-soldats-plomb', 'Figurines historiques', 'figurines historiques', ARRAY['soldats de plomb','dioramas historiques']::text[], 'active', 'curated', false, 12, 1874, '🗃️', '#a78bfa'),
  ('collections-ex-libris', 'Ex-libris', 'ex libris', ARRAY['marques de possession','plaques de livre']::text[], 'active', 'curated', false, 12, 1875, '🗃️', '#a78bfa'),
  ('collections-buvards', 'Buvards et papeterie', 'buvards et papeterie', ARRAY['papeterie ancienne','buvard publicitaire']::text[], 'active', 'curated', false, 12, 1876, '🗃️', '#a78bfa'),
  ('collections-tickets', 'Tickets et billets', 'tickets et billets', ARRAY['billets de spectacle','titres de transport']::text[], 'active', 'curated', false, 12, 1877, '🗃️', '#a78bfa'),
  ('collections-magnets', 'Magnets et souvenirs', 'magnets et souvenirs', ARRAY['aimants de frigo','souvenirs de voyage']::text[], 'active', 'curated', false, 12, 1878, '🗃️', '#a78bfa'),
  ('collections-des-a-coudre', 'Dés à coudre', 'des a coudre', ARRAY['objets de couture anciens','mercerie ancienne']::text[], 'active', 'curated', false, 12, 1879, '🗃️', '#a78bfa'),
  ('collections-coquillages', 'Coquillages', 'coquillages', ARRAY['conchyliologie','collection de coquillages']::text[], 'active', 'curated', false, 12, 1880, '🗃️', '#a78bfa'),
  ('collections-insectes', 'Entomologie de collection', 'entomologie de collection', ARRAY['boîtes d''insectes','papillons naturalisés']::text[], 'active', 'curated', false, 12, 1881, '🗃️', '#a78bfa'),
  ('collections-herbier', 'Herbiers', 'herbiers', ARRAY['herbier','plantes séchées']::text[], 'active', 'curated', false, 11, 1882, '🗃️', '#a78bfa'),
  ('collections-echange', 'Bourses d''échange', 'bourses d echange', ARRAY['salons de collectionneurs','troc de collection']::text[], 'active', 'curated', false, 11, 1883, '🗃️', '#a78bfa'),
  ('collections-cotation', 'Cotation et estimation', 'cotation et estimation', ARRAY['estimer un objet','valeur de collection']::text[], 'active', 'curated', false, 11, 1884, '🗃️', '#a78bfa'),
  ('collections-restauration-objets', 'Restauration d''objets', 'restauration d objets', ARRAY['restaurer une pièce','conservation d''objets']::text[], 'active', 'curated', false, 11, 1885, '🗃️', '#a78bfa'),
  ('collections-vitrine', 'Présenter sa collection', 'presenter sa collection', ARRAY['vitrines','mise en valeur']::text[], 'active', 'curated', false, 11, 1886, '🗃️', '#a78bfa')
on conflict (id) do update set
  label = excluded.label,
  normalized_label = excluded.normalized_label,
  aliases = excluded.aliases,
  status = case when public.passions.status = 'archived' then public.passions.status else excluded.status end,
  source = case when public.passions.source = 'legacy' then 'legacy' else excluded.source end,
  is_broad = excluded.is_broad,
  popularity = excluded.popularity,
  sort_order = excluded.sort_order,
  emoji = excluded.emoji,
  color = excluded.color,
  updated_at = now();

insert into public.passion_relations (source_passion_id, target_passion_id, relation_type, weight)
values
  ('langues-catalan', 'langues', 'broader', 3),
  ('langues', 'langues-catalan', 'narrower', 3),
  ('langues-polonais', 'langues', 'broader', 3),
  ('langues', 'langues-polonais', 'narrower', 3),
  ('langues-tcheque', 'langues', 'broader', 3),
  ('langues', 'langues-tcheque', 'narrower', 3),
  ('langues-hongrois', 'langues', 'broader', 3),
  ('langues', 'langues-hongrois', 'narrower', 3),
  ('langues-roumain', 'langues', 'broader', 3),
  ('langues', 'langues-roumain', 'narrower', 3),
  ('langues-bulgare', 'langues', 'broader', 3),
  ('langues', 'langues-bulgare', 'narrower', 3),
  ('langues-serbo-croate', 'langues', 'broader', 3),
  ('langues', 'langues-serbo-croate', 'narrower', 3),
  ('langues-ukrainien', 'langues', 'broader', 3),
  ('langues', 'langues-ukrainien', 'narrower', 3),
  ('langues-danois', 'langues', 'broader', 3),
  ('langues', 'langues-danois', 'narrower', 3),
  ('langues-norvegien', 'langues', 'broader', 3),
  ('langues', 'langues-norvegien', 'narrower', 3),
  ('langues-finnois', 'langues', 'broader', 3),
  ('langues', 'langues-finnois', 'narrower', 3),
  ('langues-islandais', 'langues', 'broader', 3),
  ('langues', 'langues-islandais', 'narrower', 3),
  ('langues-hebreu', 'langues', 'broader', 3),
  ('langues', 'langues-hebreu', 'narrower', 3),
  ('langues-persan', 'langues', 'broader', 3),
  ('langues', 'langues-persan', 'narrower', 3),
  ('langues-vietnamien', 'langues', 'broader', 3),
  ('langues', 'langues-vietnamien', 'narrower', 3),
  ('langues-thai', 'langues', 'broader', 3),
  ('langues', 'langues-thai', 'narrower', 3),
  ('langues-indonesien', 'langues', 'broader', 3),
  ('langues', 'langues-indonesien', 'narrower', 3),
  ('langues-swahili', 'langues', 'broader', 3),
  ('langues', 'langues-swahili', 'narrower', 3),
  ('langues-wolof', 'langues', 'broader', 3),
  ('langues', 'langues-wolof', 'narrower', 3),
  ('langues-amharique', 'langues', 'broader', 3),
  ('langues', 'langues-amharique', 'narrower', 3),
  ('langues-bengali', 'langues', 'broader', 3),
  ('langues', 'langues-bengali', 'narrower', 3),
  ('langues-ourdou', 'langues', 'broader', 3),
  ('langues', 'langues-ourdou', 'narrower', 3),
  ('langues-tamoul', 'langues', 'broader', 3),
  ('langues', 'langues-tamoul', 'narrower', 3),
  ('langues-punjabi', 'langues', 'broader', 3),
  ('langues', 'langues-punjabi', 'narrower', 3),
  ('langues-tagalog', 'langues', 'broader', 3),
  ('langues', 'langues-tagalog', 'narrower', 3),
  ('langues-berbere', 'langues', 'broader', 3),
  ('langues', 'langues-berbere', 'narrower', 3),
  ('langues-galicien', 'langues', 'broader', 3),
  ('langues', 'langues-galicien', 'narrower', 3),
  ('langues-gallois', 'langues', 'broader', 3),
  ('langues', 'langues-gallois', 'narrower', 3),
  ('langues-irlandais', 'langues', 'broader', 3),
  ('langues', 'langues-irlandais', 'narrower', 3),
  ('langues-ecossais-gaelique', 'langues', 'broader', 3),
  ('langues', 'langues-ecossais-gaelique', 'narrower', 3),
  ('langues-picard', 'langues', 'broader', 3),
  ('langues', 'langues-picard', 'narrower', 3),
  ('langues-normand', 'langues', 'broader', 3),
  ('langues', 'langues-normand', 'narrower', 3),
  ('langues-gascon', 'langues', 'broader', 3),
  ('langues', 'langues-gascon', 'narrower', 3),
  ('langues-savoyard', 'langues', 'broader', 3),
  ('langues', 'langues-savoyard', 'narrower', 3),
  ('langues-ch-suisse-allemand', 'langues', 'broader', 3),
  ('langues', 'langues-ch-suisse-allemand', 'narrower', 3),
  ('langues-luxembourgeois', 'langues', 'broader', 3),
  ('langues', 'langues-luxembourgeois', 'narrower', 3),
  ('langues-quebecois', 'langues', 'broader', 3),
  ('langues', 'langues-quebecois', 'narrower', 3),
  ('langues-signes-internationale', 'langues', 'broader', 3),
  ('langues', 'langues-signes-internationale', 'narrower', 3),
  ('langues-braille', 'langues', 'broader', 3),
  ('langues', 'langues-braille', 'narrower', 3),
  ('langues-calligraphie-arabe', 'langues', 'broader', 3),
  ('langues', 'langues-calligraphie-arabe', 'narrower', 3),
  ('langues-ecriture-japonaise', 'langues', 'broader', 3),
  ('langues', 'langues-ecriture-japonaise', 'narrower', 3),
  ('langues-hieroglyphes', 'langues', 'broader', 3),
  ('langues', 'langues-hieroglyphes', 'narrower', 3),
  ('langues-sanskrit', 'langues', 'broader', 3),
  ('langues', 'langues-sanskrit', 'narrower', 3),
  ('langues-gotique', 'langues', 'broader', 3),
  ('langues', 'langues-gotique', 'narrower', 3),
  ('langues-vocabulaire', 'langues', 'broader', 3),
  ('langues', 'langues-vocabulaire', 'narrower', 3),
  ('langues-expressions', 'langues', 'broader', 3),
  ('langues', 'langues-expressions', 'narrower', 3),
  ('langues-faux-amis', 'langues', 'broader', 3),
  ('langues', 'langues-faux-amis', 'narrower', 3),
  ('langues-conjugaison', 'langues', 'broader', 3),
  ('langues', 'langues-conjugaison', 'narrower', 3),
  ('langues-dictee', 'langues', 'broader', 3),
  ('langues', 'langues-dictee', 'narrower', 3),
  ('langues-correspondance', 'langues', 'broader', 3),
  ('langues', 'langues-correspondance', 'narrower', 3),
  ('langues-preparation-toeic', 'langues', 'broader', 3),
  ('langues', 'langues-preparation-toeic', 'narrower', 3),
  ('langues-langue-maternelle', 'langues', 'broader', 3),
  ('langues', 'langues-langue-maternelle', 'narrower', 3),
  ('langues-argot', 'langues', 'broader', 3),
  ('langues', 'langues-argot', 'narrower', 3),
  ('langues-toponymie', 'langues', 'broader', 3),
  ('langues', 'langues-toponymie', 'narrower', 3),
  ('langues-onomastique', 'langues', 'broader', 3),
  ('langues', 'langues-onomastique', 'narrower', 3),
  ('apprentissage-fiches', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-fiches', 'narrower', 3),
  ('apprentissage-mind-mapping', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-mind-mapping', 'narrower', 3),
  ('apprentissage-concentration', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-concentration', 'narrower', 3),
  ('apprentissage-pomodoro', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-pomodoro', 'narrower', 3),
  ('apprentissage-procrastination', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-procrastination', 'narrower', 3),
  ('apprentissage-oral', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-oral', 'narrower', 3),
  ('apprentissage-memoire-these', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-memoire-these', 'narrower', 3),
  ('apprentissage-recherche', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-recherche', 'narrower', 3),
  ('apprentissage-methodologie-sources', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-methodologie-sources', 'narrower', 3),
  ('apprentissage-apprendre-adulte', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-apprendre-adulte', 'narrower', 3),
  ('apprentissage-alternance', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-alternance', 'narrower', 3),
  ('apprentissage-orientation', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-orientation', 'narrower', 3),
  ('apprentissage-erasmus', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-erasmus', 'narrower', 3),
  ('apprentissage-tutorat', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-tutorat', 'narrower', 3),
  ('apprentissage-groupe-etude', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-groupe-etude', 'narrower', 3),
  ('apprentissage-classe-inversee', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-classe-inversee', 'narrower', 3),
  ('apprentissage-serious-game', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-serious-game', 'narrower', 3),
  ('apprentissage-carnet', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-carnet', 'narrower', 3),
  ('apprentissage-veille', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-veille', 'narrower', 3),
  ('apprentissage-bibliotheque-perso', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-bibliotheque-perso', 'narrower', 3),
  ('apprentissage-podcast-savoir', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-podcast-savoir', 'narrower', 3),
  ('apprentissage-quiz', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-quiz', 'narrower', 3),
  ('apprentissage-competition-savoir', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-competition-savoir', 'narrower', 3),
  ('apprentissage-transmission', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-transmission', 'narrower', 3),
  ('apprentissage-benevolat-education', 'apprentissage', 'broader', 3),
  ('apprentissage', 'apprentissage-benevolat-education', 'narrower', 3),
  ('philosophie-antique', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-antique', 'narrower', 3),
  ('philosophie-epicurisme', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-epicurisme', 'narrower', 3),
  ('philosophie-existentialisme', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-existentialisme', 'narrower', 3),
  ('philosophie-phenomenologie', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-phenomenologie', 'narrower', 3),
  ('philosophie-politique', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-politique', 'narrower', 3),
  ('philosophie-esthetique', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-esthetique', 'narrower', 3),
  ('philosophie-logique', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-logique', 'narrower', 3),
  ('philosophie-metaphysique', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-metaphysique', 'narrower', 3),
  ('philosophie-orientale', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-orientale', 'narrower', 3),
  ('philosophie-cafe-philo', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-cafe-philo', 'narrower', 3),
  ('philosophie-sagesse', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-sagesse', 'narrower', 3),
  ('philosophie-psychanalyse', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-psychanalyse', 'narrower', 3),
  ('philosophie-neurosciences-esprit', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-neurosciences-esprit', 'narrower', 3),
  ('philosophie-utopies', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-utopies', 'narrower', 3),
  ('philosophie-futurologie', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-futurologie', 'narrower', 3),
  ('philosophie-ecologie-pensee', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-ecologie-pensee', 'narrower', 3),
  ('philosophie-feminisme-idees', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-feminisme-idees', 'narrower', 3),
  ('philosophie-droit-idees', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-droit-idees', 'narrower', 3),
  ('philosophie-economie-idees', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-economie-idees', 'narrower', 3),
  ('philosophie-lecture-classiques', 'interiorite-philosophie', 'broader', 3),
  ('interiorite-philosophie', 'philosophie-lecture-classiques', 'narrower', 3)
on conflict (source_passion_id, target_passion_id, relation_type) do nothing;

insert into public.passion_relations (source_passion_id, target_passion_id, relation_type, weight)
values
  ('eloquence-debat', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-debat', 'narrower', 3),
  ('eloquence-argumentation', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-argumentation', 'narrower', 3),
  ('eloquence-improvisation-oratoire', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-improvisation-oratoire', 'narrower', 3),
  ('eloquence-trac', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-trac', 'narrower', 3),
  ('eloquence-storytelling', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-storytelling', 'narrower', 3),
  ('eloquence-pitch', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-pitch', 'narrower', 3),
  ('eloquence-voix', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-voix', 'narrower', 3),
  ('eloquence-mediation', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-mediation', 'narrower', 3),
  ('eloquence-animation-reunion', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-animation-reunion', 'narrower', 3),
  ('eloquence-toastmasters', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-toastmasters', 'narrower', 3),
  ('eloquence-plaidoirie', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-plaidoirie', 'narrower', 3),
  ('eloquence-ecoute', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-ecoute', 'narrower', 3),
  ('eloquence-communication-non-violente', 'eloquence', 'broader', 3),
  ('eloquence', 'eloquence-communication-non-violente', 'narrower', 3),
  ('genealogie-etat-civil', 'histoire-genealogie', 'broader', 3),
  ('histoire-genealogie', 'genealogie-etat-civil', 'narrower', 3),
  ('genealogie-adn', 'histoire-genealogie', 'broader', 3),
  ('histoire-genealogie', 'genealogie-adn', 'narrower', 3),
  ('genealogie-histoire-familiale', 'histoire-genealogie', 'broader', 3),
  ('histoire-genealogie', 'genealogie-histoire-familiale', 'narrower', 3),
  ('genealogie-photos-anciennes', 'histoire-genealogie', 'broader', 3),
  ('histoire-genealogie', 'genealogie-photos-anciennes', 'narrower', 3),
  ('genealogie-migrations', 'histoire-genealogie', 'broader', 3),
  ('histoire-genealogie', 'genealogie-migrations', 'narrower', 3),
  ('genealogie-noms-lieux', 'histoire-genealogie', 'broader', 3),
  ('histoire-genealogie', 'genealogie-noms-lieux', 'narrower', 3),
  ('genealogie-recits-oraux', 'histoire-genealogie', 'broader', 3),
  ('histoire-genealogie', 'genealogie-recits-oraux', 'narrower', 3),
  ('genealogie-numerisation', 'histoire-genealogie', 'broader', 3),
  ('histoire-genealogie', 'genealogie-numerisation', 'narrower', 3),
  ('geographie-demographie', 'sciences-geographie', 'broader', 3),
  ('sciences-geographie', 'geographie-demographie', 'narrower', 3),
  ('geographie-urbanisme-savoir', 'sciences-geographie', 'broader', 3),
  ('sciences-geographie', 'geographie-urbanisme-savoir', 'narrower', 3),
  ('geographie-toponymes', 'sciences-geographie', 'broader', 3),
  ('sciences-geographie', 'geographie-toponymes', 'narrower', 3),
  ('geographie-globes', 'sciences-geographie', 'broader', 3),
  ('sciences-geographie', 'geographie-globes', 'narrower', 3),
  ('geographie-exploration', 'sciences-geographie', 'broader', 3),
  ('sciences-geographie', 'geographie-exploration', 'narrower', 3),
  ('geographie-geocaching-savoir', 'sciences-geographie', 'broader', 3),
  ('sciences-geographie', 'geographie-geocaching-savoir', 'narrower', 3),
  ('geographie-hydrographie', 'sciences-geographie', 'broader', 3),
  ('sciences-geographie', 'geographie-hydrographie', 'narrower', 3),
  ('geographie-montagnes', 'sciences-geographie', 'broader', 3),
  ('sciences-geographie', 'geographie-montagnes', 'narrower', 3),
  ('documentation-bibliotheconomie', 'documentation', 'broader', 3),
  ('documentation', 'documentation-bibliotheconomie', 'narrower', 3),
  ('documentation-wikipedia', 'documentation', 'broader', 3),
  ('documentation', 'documentation-wikipedia', 'narrower', 3),
  ('documentation-open-data', 'documentation', 'broader', 3),
  ('documentation', 'documentation-open-data', 'narrower', 3),
  ('documentation-veille-juridique', 'documentation', 'broader', 3),
  ('documentation', 'documentation-veille-juridique', 'narrower', 3),
  ('documentation-administratif', 'documentation', 'broader', 3),
  ('documentation', 'documentation-administratif', 'narrower', 3),
  ('documentation-securite-numerique', 'documentation', 'broader', 3),
  ('documentation', 'documentation-securite-numerique', 'narrower', 3),
  ('documentation-reparation-savoir', 'documentation', 'broader', 3),
  ('documentation', 'documentation-reparation-savoir', 'narrower', 3),
  ('documentation-encyclopedisme', 'documentation', 'broader', 3),
  ('documentation', 'documentation-encyclopedisme', 'narrower', 3),
  ('collections-etiquettes-biere', 'collections', 'broader', 3),
  ('collections', 'collections-etiquettes-biere', 'narrower', 3),
  ('collections-des', 'collections', 'broader', 3),
  ('collections', 'collections-des', 'narrower', 3),
  ('collections-stylos', 'collections', 'broader', 3),
  ('collections', 'collections-stylos', 'narrower', 3),
  ('collections-cartes-a-jouer', 'collections', 'broader', 3),
  ('collections', 'collections-cartes-a-jouer', 'narrower', 3),
  ('collections-boites', 'collections', 'broader', 3),
  ('collections', 'collections-boites', 'narrower', 3),
  ('collections-cles', 'collections', 'broader', 3),
  ('collections', 'collections-cles', 'narrower', 3),
  ('collections-outils-anciens', 'collections', 'broader', 3),
  ('collections', 'collections-outils-anciens', 'narrower', 3),
  ('collections-instruments-scientifiques', 'collections', 'broader', 3),
  ('collections', 'collections-instruments-scientifiques', 'narrower', 3),
  ('collections-globes-terrestres', 'collections', 'broader', 3),
  ('collections', 'collections-globes-terrestres', 'narrower', 3),
  ('collections-textile-ancien', 'collections', 'broader', 3),
  ('collections', 'collections-textile-ancien', 'narrower', 3),
  ('collections-bijoux-anciens', 'collections', 'broader', 3),
  ('collections', 'collections-bijoux-anciens', 'narrower', 3),
  ('collections-disques-45', 'collections', 'broader', 3),
  ('collections', 'collections-disques-45', 'narrower', 3),
  ('collections-partitions', 'collections', 'broader', 3),
  ('collections', 'collections-partitions', 'narrower', 3),
  ('collections-journaux', 'collections', 'broader', 3),
  ('collections', 'collections-journaux', 'narrower', 3),
  ('collections-fanzines', 'collections', 'broader', 3),
  ('collections', 'collections-fanzines', 'narrower', 3),
  ('collections-billets', 'collections', 'broader', 3),
  ('collections', 'collections-billets', 'narrower', 3),
  ('collections-medailles', 'collections', 'broader', 3),
  ('collections', 'collections-medailles', 'narrower', 3),
  ('collections-badges', 'collections', 'broader', 3),
  ('collections', 'collections-badges', 'narrower', 3),
  ('collections-emballages', 'collections', 'broader', 3),
  ('collections', 'collections-emballages', 'narrower', 3),
  ('collections-vaisselle-emaillee', 'collections', 'broader', 3),
  ('collections', 'collections-vaisselle-emaillee', 'narrower', 3),
  ('collections-horlogerie-ancienne', 'collections', 'broader', 3),
  ('collections', 'collections-horlogerie-ancienne', 'narrower', 3),
  ('collections-radios-anciennes', 'collections', 'broader', 3),
  ('collections', 'collections-radios-anciennes', 'narrower', 3),
  ('collections-telephones', 'collections', 'broader', 3),
  ('collections', 'collections-telephones', 'narrower', 3),
  ('collections-machines-a-ecrire', 'collections', 'broader', 3),
  ('collections', 'collections-machines-a-ecrire', 'narrower', 3),
  ('collections-calculatrices', 'collections', 'broader', 3),
  ('collections', 'collections-calculatrices', 'narrower', 3),
  ('collections-jeux-anciens', 'collections', 'broader', 3),
  ('collections', 'collections-jeux-anciens', 'narrower', 3),
  ('collections-poupees', 'collections', 'broader', 3),
  ('collections', 'collections-poupees', 'narrower', 3),
  ('collections-peluches', 'collections', 'broader', 3),
  ('collections', 'collections-peluches', 'narrower', 3),
  ('collections-soldats-plomb', 'collections', 'broader', 3),
  ('collections', 'collections-soldats-plomb', 'narrower', 3),
  ('collections-ex-libris', 'collections', 'broader', 3),
  ('collections', 'collections-ex-libris', 'narrower', 3),
  ('collections-buvards', 'collections', 'broader', 3),
  ('collections', 'collections-buvards', 'narrower', 3),
  ('collections-tickets', 'collections', 'broader', 3),
  ('collections', 'collections-tickets', 'narrower', 3),
  ('collections-magnets', 'collections', 'broader', 3),
  ('collections', 'collections-magnets', 'narrower', 3),
  ('collections-des-a-coudre', 'collections', 'broader', 3),
  ('collections', 'collections-des-a-coudre', 'narrower', 3),
  ('collections-coquillages', 'collections', 'broader', 3),
  ('collections', 'collections-coquillages', 'narrower', 3),
  ('collections-insectes', 'collections', 'broader', 3),
  ('collections', 'collections-insectes', 'narrower', 3),
  ('collections-herbier', 'collections', 'broader', 3),
  ('collections', 'collections-herbier', 'narrower', 3),
  ('collections-echange', 'collections', 'broader', 3),
  ('collections', 'collections-echange', 'narrower', 3),
  ('collections-cotation', 'collections', 'broader', 3),
  ('collections', 'collections-cotation', 'narrower', 3),
  ('collections-restauration-objets', 'collections', 'broader', 3),
  ('collections', 'collections-restauration-objets', 'narrower', 3),
  ('collections-vitrine', 'collections', 'broader', 3),
  ('collections', 'collections-vitrine', 'narrower', 3)
on conflict (source_passion_id, target_passion_id, relation_type) do nothing;

-- ── Verdict ────────────────────────────────────────────────────────────────
select
  (select count(*) from public.passions where status = 'active') as passions_actives,
  2088 as attendu_au_moins,
  case when (select count(*) from public.passions where status = 'active') >= 2088
       then 'OK' else 'ECHEC' end as verdict;

commit;
