\pset format unaligned
\pset tuples_only on
\pset fieldsep '|'
select 'TOTAL|analytics_events|' || count(*) from public.analytics_events;
begin; set local role anon; select 'ANON_SELECT|analytics_events|' || count(*) from public.analytics_events; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|analytics_events|' || count(*) from public.analytics_events; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|analytics_events|' || count(*) from public.analytics_events; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.analytics_events set id = id returning 1) select 'B_UPDATE|analytics_events|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.analytics_events returning 1) select 'B_DELETE|analytics_events|' || count(*) from d; rollback;
select 'TOTAL|blocks|' || count(*) from public.blocks;
begin; set local role anon; select 'ANON_SELECT|blocks|' || count(*) from public.blocks; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|blocks|' || count(*) from public.blocks; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|blocks|' || count(*) from public.blocks; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.blocks set blocker_id = blocker_id returning 1) select 'B_UPDATE|blocks|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.blocks returning 1) select 'B_DELETE|blocks|' || count(*) from d; rollback;
select 'TOTAL|cdv_live_collaborators|' || count(*) from public.cdv_live_collaborators;
begin; set local role anon; select 'ANON_SELECT|cdv_live_collaborators|' || count(*) from public.cdv_live_collaborators; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|cdv_live_collaborators|' || count(*) from public.cdv_live_collaborators; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|cdv_live_collaborators|' || count(*) from public.cdv_live_collaborators; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.cdv_live_collaborators set live_id = live_id returning 1) select 'B_UPDATE|cdv_live_collaborators|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.cdv_live_collaborators returning 1) select 'B_DELETE|cdv_live_collaborators|' || count(*) from d; rollback;
select 'TOTAL|cdv_live_comments|' || count(*) from public.cdv_live_comments;
begin; set local role anon; select 'ANON_SELECT|cdv_live_comments|' || count(*) from public.cdv_live_comments; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|cdv_live_comments|' || count(*) from public.cdv_live_comments; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|cdv_live_comments|' || count(*) from public.cdv_live_comments; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.cdv_live_comments set id = id returning 1) select 'B_UPDATE|cdv_live_comments|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.cdv_live_comments returning 1) select 'B_DELETE|cdv_live_comments|' || count(*) from d; rollback;
select 'TOTAL|cdv_live_followers|' || count(*) from public.cdv_live_followers;
begin; set local role anon; select 'ANON_SELECT|cdv_live_followers|' || count(*) from public.cdv_live_followers; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|cdv_live_followers|' || count(*) from public.cdv_live_followers; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|cdv_live_followers|' || count(*) from public.cdv_live_followers; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.cdv_live_followers set live_id = live_id returning 1) select 'B_UPDATE|cdv_live_followers|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.cdv_live_followers returning 1) select 'B_DELETE|cdv_live_followers|' || count(*) from d; rollback;
select 'TOTAL|cdv_live_reactions|' || count(*) from public.cdv_live_reactions;
begin; set local role anon; select 'ANON_SELECT|cdv_live_reactions|' || count(*) from public.cdv_live_reactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|cdv_live_reactions|' || count(*) from public.cdv_live_reactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|cdv_live_reactions|' || count(*) from public.cdv_live_reactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.cdv_live_reactions set id = id returning 1) select 'B_UPDATE|cdv_live_reactions|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.cdv_live_reactions returning 1) select 'B_DELETE|cdv_live_reactions|' || count(*) from d; rollback;
select 'TOTAL|cdv_live_steps|' || count(*) from public.cdv_live_steps;
begin; set local role anon; select 'ANON_SELECT|cdv_live_steps|' || count(*) from public.cdv_live_steps; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|cdv_live_steps|' || count(*) from public.cdv_live_steps; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|cdv_live_steps|' || count(*) from public.cdv_live_steps; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.cdv_live_steps set id = id returning 1) select 'B_UPDATE|cdv_live_steps|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.cdv_live_steps returning 1) select 'B_DELETE|cdv_live_steps|' || count(*) from d; rollback;
select 'TOTAL|cdv_lives|' || count(*) from public.cdv_lives;
begin; set local role anon; select 'ANON_SELECT|cdv_lives|' || count(*) from public.cdv_lives; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|cdv_lives|' || count(*) from public.cdv_lives; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|cdv_lives|' || count(*) from public.cdv_lives; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.cdv_lives set id = id returning 1) select 'B_UPDATE|cdv_lives|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.cdv_lives returning 1) select 'B_DELETE|cdv_lives|' || count(*) from d; rollback;
select 'TOTAL|client_errors|' || count(*) from public.client_errors;
begin; set local role anon; select 'ANON_SELECT|client_errors|' || count(*) from public.client_errors; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|client_errors|' || count(*) from public.client_errors; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|client_errors|' || count(*) from public.client_errors; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.client_errors set id = id returning 1) select 'B_UPDATE|client_errors|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.client_errors returning 1) select 'B_DELETE|client_errors|' || count(*) from d; rollback;
select 'TOTAL|comment_interactions|' || count(*) from public.comment_interactions;
begin; set local role anon; select 'ANON_SELECT|comment_interactions|' || count(*) from public.comment_interactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|comment_interactions|' || count(*) from public.comment_interactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|comment_interactions|' || count(*) from public.comment_interactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.comment_interactions set id = id returning 1) select 'B_UPDATE|comment_interactions|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.comment_interactions returning 1) select 'B_DELETE|comment_interactions|' || count(*) from d; rollback;
select 'TOTAL|comment_likes|' || count(*) from public.comment_likes;
begin; set local role anon; select 'ANON_SELECT|comment_likes|' || count(*) from public.comment_likes; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|comment_likes|' || count(*) from public.comment_likes; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|comment_likes|' || count(*) from public.comment_likes; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.comment_likes set comment_id = comment_id returning 1) select 'B_UPDATE|comment_likes|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.comment_likes returning 1) select 'B_DELETE|comment_likes|' || count(*) from d; rollback;
select 'TOTAL|conv_members|' || count(*) from public.conv_members;
begin; set local role anon; select 'ANON_SELECT|conv_members|' || count(*) from public.conv_members; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|conv_members|' || count(*) from public.conv_members; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|conv_members|' || count(*) from public.conv_members; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.conv_members set conv_id = conv_id returning 1) select 'B_UPDATE|conv_members|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.conv_members returning 1) select 'B_DELETE|conv_members|' || count(*) from d; rollback;
select 'TOTAL|conv_messages|' || count(*) from public.conv_messages;
begin; set local role anon; select 'ANON_SELECT|conv_messages|' || count(*) from public.conv_messages; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|conv_messages|' || count(*) from public.conv_messages; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|conv_messages|' || count(*) from public.conv_messages; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.conv_messages set id = id returning 1) select 'B_UPDATE|conv_messages|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.conv_messages returning 1) select 'B_DELETE|conv_messages|' || count(*) from d; rollback;
select 'TOTAL|conv_reads|' || count(*) from public.conv_reads;
begin; set local role anon; select 'ANON_SELECT|conv_reads|' || count(*) from public.conv_reads; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|conv_reads|' || count(*) from public.conv_reads; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|conv_reads|' || count(*) from public.conv_reads; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.conv_reads set conv_id = conv_id returning 1) select 'B_UPDATE|conv_reads|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.conv_reads returning 1) select 'B_DELETE|conv_reads|' || count(*) from d; rollback;
select 'TOTAL|conversations|' || count(*) from public.conversations;
begin; set local role anon; select 'ANON_SELECT|conversations|' || count(*) from public.conversations; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|conversations|' || count(*) from public.conversations; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|conversations|' || count(*) from public.conversations; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.conversations set id = id returning 1) select 'B_UPDATE|conversations|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.conversations returning 1) select 'B_DELETE|conversations|' || count(*) from d; rollback;
select 'TOTAL|event_attendees|' || count(*) from public.event_attendees;
begin; set local role anon; select 'ANON_SELECT|event_attendees|' || count(*) from public.event_attendees; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|event_attendees|' || count(*) from public.event_attendees; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|event_attendees|' || count(*) from public.event_attendees; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.event_attendees set event_id = event_id returning 1) select 'B_UPDATE|event_attendees|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.event_attendees returning 1) select 'B_DELETE|event_attendees|' || count(*) from d; rollback;
select 'TOTAL|event_comments|' || count(*) from public.event_comments;
begin; set local role anon; select 'ANON_SELECT|event_comments|' || count(*) from public.event_comments; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|event_comments|' || count(*) from public.event_comments; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|event_comments|' || count(*) from public.event_comments; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.event_comments set id = id returning 1) select 'B_UPDATE|event_comments|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.event_comments returning 1) select 'B_DELETE|event_comments|' || count(*) from d; rollback;
select 'TOTAL|event_reactions|' || count(*) from public.event_reactions;
begin; set local role anon; select 'ANON_SELECT|event_reactions|' || count(*) from public.event_reactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|event_reactions|' || count(*) from public.event_reactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|event_reactions|' || count(*) from public.event_reactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.event_reactions set event_id = event_id returning 1) select 'B_UPDATE|event_reactions|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.event_reactions returning 1) select 'B_DELETE|event_reactions|' || count(*) from d; rollback;
select 'TOTAL|events|' || count(*) from public.events;
begin; set local role anon; select 'ANON_SELECT|events|' || count(*) from public.events; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|events|' || count(*) from public.events; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|events|' || count(*) from public.events; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.events set id = id returning 1) select 'B_UPDATE|events|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.events returning 1) select 'B_DELETE|events|' || count(*) from d; rollback;
select 'TOTAL|follows|' || count(*) from public.follows;
begin; set local role anon; select 'ANON_SELECT|follows|' || count(*) from public.follows; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|follows|' || count(*) from public.follows; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|follows|' || count(*) from public.follows; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.follows set follower_id = follower_id returning 1) select 'B_UPDATE|follows|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.follows returning 1) select 'B_DELETE|follows|' || count(*) from d; rollback;
select 'TOTAL|notifications|' || count(*) from public.notifications;
begin; set local role anon; select 'ANON_SELECT|notifications|' || count(*) from public.notifications; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|notifications|' || count(*) from public.notifications; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|notifications|' || count(*) from public.notifications; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.notifications set id = id returning 1) select 'B_UPDATE|notifications|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.notifications returning 1) select 'B_DELETE|notifications|' || count(*) from d; rollback;
select 'TOTAL|passion_relations|' || count(*) from public.passion_relations;
begin; set local role anon; select 'ANON_SELECT|passion_relations|' || count(*) from public.passion_relations; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|passion_relations|' || count(*) from public.passion_relations; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|passion_relations|' || count(*) from public.passion_relations; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.passion_relations set source_passion_id = source_passion_id returning 1) select 'B_UPDATE|passion_relations|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.passion_relations returning 1) select 'B_DELETE|passion_relations|' || count(*) from d; rollback;
select 'TOTAL|passion_requests|' || count(*) from public.passion_requests;
begin; set local role anon; select 'ANON_SELECT|passion_requests|' || count(*) from public.passion_requests; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|passion_requests|' || count(*) from public.passion_requests; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|passion_requests|' || count(*) from public.passion_requests; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.passion_requests set id = id returning 1) select 'B_UPDATE|passion_requests|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.passion_requests returning 1) select 'B_DELETE|passion_requests|' || count(*) from d; rollback;
select 'TOTAL|passions|' || count(*) from public.passions;
begin; set local role anon; select 'ANON_SELECT|passions|' || count(*) from public.passions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|passions|' || count(*) from public.passions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|passions|' || count(*) from public.passions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.passions set id = id returning 1) select 'B_UPDATE|passions|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.passions returning 1) select 'B_DELETE|passions|' || count(*) from d; rollback;
select 'TOTAL|post_collaborators|' || count(*) from public.post_collaborators;
begin; set local role anon; select 'ANON_SELECT|post_collaborators|' || count(*) from public.post_collaborators; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|post_collaborators|' || count(*) from public.post_collaborators; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|post_collaborators|' || count(*) from public.post_collaborators; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.post_collaborators set post_id = post_id returning 1) select 'B_UPDATE|post_collaborators|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.post_collaborators returning 1) select 'B_DELETE|post_collaborators|' || count(*) from d; rollback;
select 'TOTAL|post_comments|' || count(*) from public.post_comments;
begin; set local role anon; select 'ANON_SELECT|post_comments|' || count(*) from public.post_comments; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|post_comments|' || count(*) from public.post_comments; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|post_comments|' || count(*) from public.post_comments; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.post_comments set id = id returning 1) select 'B_UPDATE|post_comments|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.post_comments returning 1) select 'B_DELETE|post_comments|' || count(*) from d; rollback;
select 'TOTAL|post_likes|' || count(*) from public.post_likes;
begin; set local role anon; select 'ANON_SELECT|post_likes|' || count(*) from public.post_likes; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|post_likes|' || count(*) from public.post_likes; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|post_likes|' || count(*) from public.post_likes; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.post_likes set post_id = post_id returning 1) select 'B_UPDATE|post_likes|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.post_likes returning 1) select 'B_DELETE|post_likes|' || count(*) from d; rollback;
select 'TOTAL|posts|' || count(*) from public.posts;
begin; set local role anon; select 'ANON_SELECT|posts|' || count(*) from public.posts; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|posts|' || count(*) from public.posts; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|posts|' || count(*) from public.posts; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.posts set id = id returning 1) select 'B_UPDATE|posts|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.posts returning 1) select 'B_DELETE|posts|' || count(*) from d; rollback;
select 'TOTAL|profiles|' || count(*) from public.profiles;
begin; set local role anon; select 'ANON_SELECT|profiles|' || count(*) from public.profiles; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|profiles|' || count(*) from public.profiles; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|profiles|' || count(*) from public.profiles; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.profiles set id = id returning 1) select 'B_UPDATE|profiles|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.profiles returning 1) select 'B_DELETE|profiles|' || count(*) from d; rollback;
select 'TOTAL|push_subscriptions|' || count(*) from public.push_subscriptions;
begin; set local role anon; select 'ANON_SELECT|push_subscriptions|' || count(*) from public.push_subscriptions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|push_subscriptions|' || count(*) from public.push_subscriptions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|push_subscriptions|' || count(*) from public.push_subscriptions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.push_subscriptions set endpoint = endpoint returning 1) select 'B_UPDATE|push_subscriptions|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.push_subscriptions returning 1) select 'B_DELETE|push_subscriptions|' || count(*) from d; rollback;
select 'TOTAL|reports|' || count(*) from public.reports;
begin; set local role anon; select 'ANON_SELECT|reports|' || count(*) from public.reports; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|reports|' || count(*) from public.reports; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|reports|' || count(*) from public.reports; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.reports set id = id returning 1) select 'B_UPDATE|reports|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.reports returning 1) select 'B_DELETE|reports|' || count(*) from d; rollback;
select 'TOTAL|step_interactions|' || count(*) from public.step_interactions;
begin; set local role anon; select 'ANON_SELECT|step_interactions|' || count(*) from public.step_interactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|step_interactions|' || count(*) from public.step_interactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|step_interactions|' || count(*) from public.step_interactions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.step_interactions set id = id returning 1) select 'B_UPDATE|step_interactions|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.step_interactions returning 1) select 'B_DELETE|step_interactions|' || count(*) from d; rollback;
select 'TOTAL|stories|' || count(*) from public.stories;
begin; set local role anon; select 'ANON_SELECT|stories|' || count(*) from public.stories; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|stories|' || count(*) from public.stories; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|stories|' || count(*) from public.stories; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.stories set id = id returning 1) select 'B_UPDATE|stories|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.stories returning 1) select 'B_DELETE|stories|' || count(*) from d; rollback;
select 'TOTAL|story_views|' || count(*) from public.story_views;
begin; set local role anon; select 'ANON_SELECT|story_views|' || count(*) from public.story_views; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|story_views|' || count(*) from public.story_views; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|story_views|' || count(*) from public.story_views; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.story_views set story_id = story_id returning 1) select 'B_UPDATE|story_views|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.story_views returning 1) select 'B_DELETE|story_views|' || count(*) from d; rollback;
select 'TOTAL|telemetry_events|' || count(*) from public.telemetry_events;
begin; set local role anon; select 'ANON_SELECT|telemetry_events|' || count(*) from public.telemetry_events; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|telemetry_events|' || count(*) from public.telemetry_events; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|telemetry_events|' || count(*) from public.telemetry_events; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.telemetry_events set id = id returning 1) select 'B_UPDATE|telemetry_events|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.telemetry_events returning 1) select 'B_DELETE|telemetry_events|' || count(*) from d; rollback;
select 'TOTAL|user_passions|' || count(*) from public.user_passions;
begin; set local role anon; select 'ANON_SELECT|user_passions|' || count(*) from public.user_passions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|user_passions|' || count(*) from public.user_passions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|user_passions|' || count(*) from public.user_passions; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.user_passions set user_id = user_id returning 1) select 'B_UPDATE|user_passions|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.user_passions returning 1) select 'B_DELETE|user_passions|' || count(*) from d; rollback;
select 'TOTAL|user_safety|' || count(*) from public.user_safety;
begin; set local role anon; select 'ANON_SELECT|user_safety|' || count(*) from public.user_safety; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|user_safety|' || count(*) from public.user_safety; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|user_safety|' || count(*) from public.user_safety; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.user_safety set user_id = user_id returning 1) select 'B_UPDATE|user_safety|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.user_safety returning 1) select 'B_DELETE|user_safety|' || count(*) from d; rollback;
select 'TOTAL|user_state|' || count(*) from public.user_state;
begin; set local role anon; select 'ANON_SELECT|user_state|' || count(*) from public.user_state; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|user_state|' || count(*) from public.user_state; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|user_state|' || count(*) from public.user_state; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.user_state set user_id = user_id returning 1) select 'B_UPDATE|user_state|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.user_state returning 1) select 'B_DELETE|user_state|' || count(*) from d; rollback;
select 'TOTAL|video_lives|' || count(*) from public.video_lives;
begin; set local role anon; select 'ANON_SELECT|video_lives|' || count(*) from public.video_lives; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|video_lives|' || count(*) from public.video_lives; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|video_lives|' || count(*) from public.video_lives; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update public.video_lives set id = id returning 1) select 'B_UPDATE|video_lives|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from public.video_lives returning 1) select 'B_DELETE|video_lives|' || count(*) from d; rollback;
select 'TOTAL|storage.objects|' || count(*) from storage.objects;
begin; set local role anon; select 'ANON_SELECT|storage.objects|' || count(*) from storage.objects; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; select 'B_SELECT|storage.objects|' || count(*) from storage.objects; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'; select 'A_SELECT|storage.objects|' || count(*) from storage.objects; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with u as (update storage.objects set name = name returning 1) select 'B_UPDATE|storage.objects|' || count(*) from u; rollback;
begin; set local role authenticated; set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'; with d as (delete from storage.objects returning 1) select 'B_DELETE|storage.objects|' || count(*) from d; rollback;