
-- ===== SOCLE Supabase minimal (roles, auth.uid, storage, realtime stub) =====
CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN;
GRANT USAGE ON SCHEMA public TO anon, authenticated;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
GRANT USAGE ON SCHEMA auth TO anon, authenticated;
CREATE SCHEMA storage;
CREATE TABLE storage.buckets (id text primary key, name text, public boolean default false);
CREATE TABLE storage.objects (id uuid default gen_random_uuid() primary key, bucket_id text, name text, owner uuid, created_at timestamptz default now(), metadata jsonb);
CREATE FUNCTION storage.foldername(name text) RETURNS text[] LANGUAGE plpgsql IMMUTABLE AS $$ DECLARE _parts text[]; BEGIN SELECT string_to_array(name, '/') INTO _parts; RETURN _parts[1:array_length(_parts,1)-1]; END $$;
GRANT USAGE ON SCHEMA storage TO anon, authenticated;
GRANT ALL ON storage.objects, storage.buckets TO anon, authenticated;
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
ALTER TABLE storage.buckets ENABLE ROW LEVEL SECURITY;
INSERT INTO storage.buckets VALUES ('content','content',true), ('attachments','attachments',true);

-- ===== TABLES RÉELLES (colonnes de production, 2026-09-08) =====
CREATE TABLE public.analytics_events (id uuid NOT NULL DEFAULT gen_random_uuid(), user_id text NOT NULL, event text NOT NULL, properties jsonb DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.blocks (blocker_id text NOT NULL, blocked_id text NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY (blocker_id, blocked_id));
CREATE TABLE public.cdv_live_collaborators (live_id text NOT NULL, user_id text NOT NULL, added_by text NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY (live_id, user_id));
CREATE TABLE public.cdv_live_comments (id text NOT NULL, live_id text NOT NULL, author_id text NOT NULL, author_name text, text text, created_at timestamptz DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.cdv_live_followers (live_id text NOT NULL, user_id text NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY (live_id, user_id));
CREATE TABLE public.cdv_live_reactions (id text NOT NULL, live_id text NOT NULL, user_id text NOT NULL, emoji text, created_at timestamptz DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.cdv_live_steps (id text NOT NULL, live_id text NOT NULL, author_id text NOT NULL, city text, emoji text, content text, photos jsonb DEFAULT '[]'::jsonb, rating integer DEFAULT 0, budget text, created_at timestamptz DEFAULT now(), lat double precision, lng double precision, video text, PRIMARY KEY (id));
CREATE TABLE public.cdv_lives (id text NOT NULL, author_id text NOT NULL, destination text, description text, duration text, visibility text DEFAULT 'public'::text, status text DEFAULT 'live'::text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.client_errors (id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, message text, source text, line integer, stack text, url text, ua text, uid text, created_at timestamptz DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.comment_interactions (id text NOT NULL, comment_id text NOT NULL, post_id text, user_id text NOT NULL, kind text NOT NULL, payload text, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.comment_likes (comment_id text NOT NULL, user_id text NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY (comment_id, user_id));
CREATE TABLE public.conv_members (conv_id text NOT NULL, user_id text NOT NULL, PRIMARY KEY (conv_id, user_id));
CREATE TABLE public.conv_messages (id text NOT NULL, conv_id text, from_id text, content text, created_at timestamp DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.conv_reads (conv_id text NOT NULL, user_id text NOT NULL, last_read_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (conv_id, user_id));
CREATE TABLE public.conversations (id text NOT NULL, is_group boolean DEFAULT false, group_name text, passion_id text, created_by text, created_at timestamp DEFAULT now(), description text, PRIMARY KEY (id));
CREATE TABLE public.event_attendees (event_id text NOT NULL, user_id text NOT NULL, created_at timestamptz DEFAULT now(), rsvp text NOT NULL DEFAULT 'going'::text, checked_in_at timestamp, rating smallint, feedback text, rated_at timestamptz, PRIMARY KEY (event_id, user_id));
CREATE TABLE public.event_comments (id text NOT NULL, event_id text NOT NULL, author_id text NOT NULL, author_name text, text text, created_at timestamptz DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.event_reactions (event_id text NOT NULL, user_id text NOT NULL, emoji text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (event_id, user_id, emoji));
CREATE TABLE public.events (id text NOT NULL, author_id text, title text, passion_id text, lat double precision, lng double precision, city text, description text, emoji text DEFAULT '📍'::text, max_attendees integer, date_at timestamp, created_at timestamp DEFAULT now(), venue text, address text, postal_code text, price double precision DEFAULT 0, contact text, external_link text, event_type text DEFAULT 'Autre'::text, cover_url text, organizer_id text, end_at timestamp, status text NOT NULL DEFAULT 'active'::text, updated_at timestamp, co_organizers jsonb NOT NULL DEFAULT '[]'::jsonb, series_id text, recurrence text NOT NULL DEFAULT 'none'::text, conv_id text, PRIMARY KEY (id));
CREATE TABLE public.follows (follower_id text NOT NULL, following_id text NOT NULL, PRIMARY KEY (follower_id, following_id));
CREATE TABLE public.notifications (id text NOT NULL, user_id text, kind text, from_id text, ref_id text, content text, seen boolean DEFAULT false, created_at timestamp DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.passion_relations (source_passion_id text NOT NULL, target_passion_id text NOT NULL, relation_type text NOT NULL, weight integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (source_passion_id, target_passion_id, relation_type));
CREATE TABLE public.passion_requests (id uuid NOT NULL DEFAULT gen_random_uuid(), user_id text NOT NULL, label text NOT NULL, normalized_label text NOT NULL, status text NOT NULL DEFAULT 'pending'::text, resolved_passion_id text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.passions (id text NOT NULL, emoji text NOT NULL DEFAULT '✨'::text, label text NOT NULL, color text, sort_order integer NOT NULL DEFAULT 0, normalized_label text, aliases text[] NOT NULL DEFAULT '{}'::text[], status text NOT NULL DEFAULT 'active'::text, source text NOT NULL DEFAULT 'legacy'::text, is_broad boolean NOT NULL DEFAULT false, popularity integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.post_collaborators (post_id text NOT NULL, user_id text NOT NULL, added_by text NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY (post_id, user_id));
CREATE TABLE public.post_comments (id text NOT NULL, post_id text, author_id text, content text, created_at timestamp DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.post_likes (post_id text NOT NULL, user_id text NOT NULL, PRIMARY KEY (post_id, user_id));
CREATE TABLE public.posts (id text NOT NULL, author_id text, passion_id text, mood text, content text, media_url text, likes integer DEFAULT 0, created_at timestamp DEFAULT now(), shared_from_post_id text, shared_data text, is_reel boolean DEFAULT false, overlays jsonb, vlog jsonb, event_id text, PRIMARY KEY (id));
CREATE TABLE public.profiles (id text NOT NULL, username text NOT NULL, emoji text DEFAULT '✨'::text, color text DEFAULT '#8b5cf6'::text, passion_id text, bio text, created_at timestamp DEFAULT now(), avatar_url text, cover_url text, passions jsonb DEFAULT '[]'::jsonb, is_private boolean NOT NULL DEFAULT false, rs_links jsonb, PRIMARY KEY (id));
CREATE TABLE public.push_subscriptions (endpoint text NOT NULL, user_id text NOT NULL, subscription jsonb NOT NULL, created_at timestamptz DEFAULT now(), PRIMARY KEY (endpoint));
CREATE TABLE public.reports (id text NOT NULL, reporter_id text, target_type text, target_id text, reason text, created_at timestamptz DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.step_interactions (id text NOT NULL, thread_id text NOT NULL, user_id text NOT NULL, kind text NOT NULL, content text, author_name text, author_emoji text, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (id));
CREATE TABLE public.stories (id text NOT NULL, author_id text, passion_id text, content text, emoji text DEFAULT '✨'::text, created_at timestamp DEFAULT now(), media_url text, media_type text, overlays jsonb, PRIMARY KEY (id));
CREATE TABLE public.story_views (story_id text NOT NULL, user_id text NOT NULL, seen_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (story_id, user_id));
CREATE TABLE public.telemetry_events (id uuid NOT NULL DEFAULT gen_random_uuid(), event_id text, received_at timestamptz NOT NULL DEFAULT now(), client_ts timestamptz, env text NOT NULL DEFAULT 'production'::text, type text NOT NULL, action text, screen text, status text, severity text NOT NULL DEFAULT 'info'::text, duration_ms integer, user_id text, user_label text, session_id text, device_id text, platform text, browser text, app_version text, screen_size text, connection text, endpoint text, http_status integer, correlation_id text, message text, stack text, meta jsonb NOT NULL DEFAULT '{}'::jsonb, PRIMARY KEY (id));
CREATE TABLE public.user_passions (user_id text NOT NULL, passion_id text NOT NULL, position integer NOT NULL DEFAULT 0, archived boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (user_id, passion_id));
CREATE TABLE public.user_safety (user_id text NOT NULL, majority_at date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (user_id));
CREATE TABLE public.user_state (user_id text NOT NULL, data jsonb NOT NULL DEFAULT '{}'::jsonb, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (user_id));
CREATE TABLE public.video_lives (id text NOT NULL, author_id text NOT NULL, author_name text, author_emoji text, author_photo text, title text, status text NOT NULL DEFAULT 'live'::text, started_at timestamptz NOT NULL DEFAULT now(), last_seen timestamptz NOT NULL DEFAULT now(), ended_at timestamptz, PRIMARY KEY (id));

ALTER TABLE public.passions ADD CHECK (status = ANY (ARRAY['active','archived','pending']));
ALTER TABLE public.event_attendees ADD CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5));
ALTER TABLE public.passion_relations ADD CHECK (relation_type = ANY (ARRAY['related','broader','narrower']));
ALTER TABLE public.passion_relations ADD CHECK (source_passion_id <> target_passion_id);
ALTER TABLE public.passion_requests ADD CHECK (status = ANY (ARRAY['pending','approved','rejected','duplicate']));
ALTER TABLE public.comment_interactions ADD CHECK (kind = ANY (ARRAY['like','reply','emoji','gif']));
-- Grants par défaut Supabase : anon et authenticated ont TOUS les droits sur les tables, la RLS est la seule barrière.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cdv_live_collaborators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cdv_live_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cdv_live_followers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cdv_live_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cdv_live_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cdv_lives ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_errors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comment_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comment_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conv_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conv_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conv_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_attendees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passion_relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passion_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.passions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_collaborators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.step_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.story_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_passions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_safety ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.video_lives ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.can_edit_post(pid text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$
  SELECT EXISTS (SELECT 1 FROM posts p WHERE p.id = pid AND p.author_id = auth.uid()::text)
      OR EXISTS (SELECT 1 FROM post_collaborators c WHERE c.post_id = pid AND c.user_id = auth.uid()::text);
$function$;
CREATE OR REPLACE FUNCTION public.is_blocked_with(_other text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
  SELECT CASE WHEN auth.uid() IS NULL OR _other IS NULL OR _other = (auth.uid())::text THEN FALSE
    ELSE EXISTS (SELECT 1 FROM public.blocks b WHERE (b.blocker_id = (auth.uid())::text AND b.blocked_id = _other) OR (b.blocker_id = _other AND b.blocked_id = (auth.uid())::text)) END
$function$;
CREATE OR REPLACE FUNCTION public.can_join_event_conversation(_conv_id text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
  SELECT CASE WHEN auth.uid() IS NULL OR _conv_id IS NULL THEN FALSE
    ELSE EXISTS (SELECT 1 FROM public.events e JOIN public.event_attendees a ON a.event_id = e.id AND a.user_id = (auth.uid())::text JOIN public.conversations c ON c.id = e.conv_id
       WHERE e.conv_id = _conv_id AND e.conv_id = ('evgrp_' || e.id) AND c.created_by = e.author_id AND e.status = 'active' AND a.rsvp IN ('going', 'maybe') AND NOT public.is_blocked_with(e.author_id)) END
$function$;
CREATE OR REPLACE FUNCTION public.post_is_visible(pid text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$
  select case when pid is null then true when not exists (select 1 from posts where id = pid) then true
    else exists (select 1 from posts p where p.id = pid and (p.author_id = (select auth.uid())::text
        or not exists (select 1 from profiles pr where pr.id = p.author_id and pr.is_private)
        or exists (select 1 from follows f where f.follower_id = (select auth.uid())::text and f.following_id = p.author_id))) end
$function$;
CREATE OR REPLACE FUNCTION public.comment_target_visible(cid text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$
  select case when cid is null then true
    when exists (select 1 from posts where id = cid) then public.post_is_visible(cid)
    when exists (select 1 from post_comments where id = cid) then public.post_is_visible((select post_id from post_comments where id = cid limit 1))
    else true end
$function$;
CREATE OR REPLACE FUNCTION public.declare_birth_year(_birth_year integer) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO '' AS $function$
DECLARE v_uid TEXT; v_candidate DATE; v_applied BOOLEAN;
BEGIN
  v_uid := (auth.uid())::text;
  IF v_uid IS NULL OR _birth_year IS NULL THEN RETURN FALSE; END IF;
  IF _birth_year < 1900 OR _birth_year > EXTRACT(YEAR FROM CURRENT_DATE)::INTEGER THEN RETURN FALSE; END IF;
  v_candidate := make_date(_birth_year + 18, 12, 31);
  INSERT INTO public.user_safety AS s (user_id, majority_at) VALUES (v_uid, v_candidate)
  ON CONFLICT (user_id) DO UPDATE SET majority_at = EXCLUDED.majority_at, updated_at = NOW()
    WHERE s.majority_at IS NULL OR EXCLUDED.majority_at > s.majority_at
  RETURNING TRUE INTO v_applied;
  RETURN COALESCE(v_applied, FALSE);
END $function$;
CREATE OR REPLACE FUNCTION public.identite_affichage_canonique() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
declare proprietaire text; p record;
begin
  proprietaire := coalesce(to_jsonb(new) ->> 'author_id', to_jsonb(new) ->> 'user_id');
  if proprietaire is null then return new; end if;
  select username, avatar_url, emoji into p from public.profiles where id = proprietaire;
  if not found then return new; end if;
  if to_jsonb(new) ? 'author_name'  then new.author_name  := p.username;   end if;
  if to_jsonb(new) ? 'author_photo' then new.author_photo := p.avatar_url; end if;
  if to_jsonb(new) ? 'author_emoji' then new.author_emoji := p.emoji;      end if;
  return new;
end; $function$;
CREATE OR REPLACE FUNCTION public.irl_interaction_allowed(_other text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
  SELECT CASE WHEN auth.uid() IS NULL OR _other IS NULL OR _other = (auth.uid())::text THEN FALSE
    WHEN public.is_blocked_with(_other) THEN FALSE
    ELSE (COALESCE((SELECT s.majority_at <= CURRENT_DATE FROM public.user_safety s WHERE s.user_id = (auth.uid())::text), FALSE)
      AND COALESCE((SELECT s.majority_at <= CURRENT_DATE FROM public.user_safety s WHERE s.user_id = _other), FALSE)) END
$function$;
CREATE OR REPLACE FUNCTION public.is_conv_member(_conv_id text, _uid text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $function$ select exists (select 1 from public.conv_members m where m.conv_id = _conv_id and m.user_id = _uid) $function$;
CREATE OR REPLACE FUNCTION public.is_conversation_creator(_conv_id text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $function$
  SELECT CASE WHEN auth.uid() IS NULL OR _conv_id IS NULL THEN FALSE ELSE EXISTS (SELECT 1 FROM public.conversations c WHERE c.id = _conv_id AND c.created_by = (auth.uid())::text) END
$function$;
CREATE OR REPLACE FUNCTION public.posts_freeze_author() RETURNS trigger LANGUAGE plpgsql SET search_path TO '' AS $function$
BEGIN IF NEW.author_id IS DISTINCT FROM OLD.author_id THEN NEW.author_id := OLD.author_id; END IF; RETURN NEW; END; $function$;
CREATE OR REPLACE FUNCTION public.propager_identite_affichage() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
begin
  update public.video_lives set author_name = new.username, author_photo = new.avatar_url, author_emoji = new.emoji where author_id = new.id;
  update public.event_comments set author_name = new.username where author_id = new.id;
  update public.cdv_live_comments set author_name = new.username where author_id = new.id;
  update public.step_interactions set author_name = new.username, author_emoji = new.emoji where user_id = new.id;
  return new;
end; $function$;
CREATE OR REPLACE FUNCTION public.rate_limit_insert() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public', 'pg_temp' AS $function$
DECLARE user_col text := TG_ARGV[0]; max_per_min int := TG_ARGV[1]::int; uid text; cnt int;
BEGIN
  NEW.created_at := now();
  EXECUTE format('SELECT ($1).%I', user_col) INTO uid USING NEW;
  IF uid IS NULL THEN RETURN NEW; END IF;
  EXECUTE format('SELECT count(*) FROM %I.%I WHERE %I = $1 AND created_at > now() - interval ''1 minute''', TG_TABLE_SCHEMA, TG_TABLE_NAME, user_col) INTO cnt USING uid;
  IF cnt >= max_per_min THEN RAISE EXCEPTION 'rate limit: max % insertions/minute sur %', max_per_min, TG_TABLE_NAME USING ERRCODE = 'P0001'; END IF;
  RETURN NEW;
END $function$;
CREATE OR REPLACE FUNCTION public.storage_chemin_autorise(_bucket text, _name text) RETURNS boolean LANGUAGE sql STABLE AS $function$
  select (_bucket = 'content' and (storage.foldername(_name))[2] = (select auth.uid())::text)
    or (_bucket = 'attachments' and public.is_conv_member((storage.foldername(_name))[2], (select auth.uid())::text));
$function$;
CREATE OR REPLACE FUNCTION public.unaccent_immutable(txt text) RETURNS text LANGUAGE sql IMMUTABLE STRICT AS $function$
  select translate(lower(txt), 'àáâãäåçèéêëìíîïñòóôõöùúûüýÿœæ', 'aaaaaaceeeeiiiinooooouuuuyyoa');
$function$;
CREATE OR REPLACE FUNCTION public.user_safety_majorite_non_avancable() RETURNS trigger LANGUAGE plpgsql SET search_path TO '' AS $function$
BEGIN
  IF OLD.majority_at IS NOT NULL AND (NEW.majority_at IS NULL OR NEW.majority_at < OLD.majority_at) THEN
    RAISE EXCEPTION 'majority_at ne peut pas etre avancee (%->%)', OLD.majority_at, NEW.majority_at USING ERRCODE = 'check_violation';
  END IF;
  NEW.updated_at := NOW(); RETURN NEW;
END $function$;
CREATE OR REPLACE FUNCTION public.user_state_horodatage_serveur() RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $function$
begin new.updated_at := now(); return new; end; $function$;
-- Grants EXECUTE tels que relevés en production le 2026-09-08 (has_function_privilege)
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.can_edit_post(text), public.comment_target_visible(text), public.is_conv_member(text,text), public.post_is_visible(text), public.storage_chemin_autorise(text,text), public.unaccent_immutable(text), public.user_state_horodatage_serveur() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.can_join_event_conversation(text), public.declare_birth_year(integer), public.irl_interaction_allowed(text), public.is_blocked_with(text), public.is_conversation_creator(text) TO authenticated;
-- Triggers réels (le broadcast realtime est remplacé par un stub : hors périmètre RLS)
CREATE TRIGGER trg_rate_limit BEFORE INSERT ON public.comment_interactions FOR EACH ROW EXECUTE FUNCTION rate_limit_insert('user_id', '60');
CREATE TRIGGER trg_rate_limit BEFORE INSERT ON public.event_reactions FOR EACH ROW EXECUTE FUNCTION rate_limit_insert('user_id', '30');
CREATE TRIGGER trg_rate_limit BEFORE INSERT ON public.reports FOR EACH ROW EXECUTE FUNCTION rate_limit_insert('reporter_id', '10');
CREATE TRIGGER trg_posts_freeze_author BEFORE UPDATE ON public.posts FOR EACH ROW EXECUTE FUNCTION posts_freeze_author();
CREATE TRIGGER trg_identite_affichage BEFORE INSERT OR UPDATE ON public.video_lives FOR EACH ROW EXECUTE FUNCTION identite_affichage_canonique();
CREATE TRIGGER trg_identite_affichage BEFORE INSERT OR UPDATE ON public.event_comments FOR EACH ROW EXECUTE FUNCTION identite_affichage_canonique();
CREATE TRIGGER trg_identite_affichage BEFORE INSERT OR UPDATE ON public.cdv_live_comments FOR EACH ROW EXECUTE FUNCTION identite_affichage_canonique();
CREATE TRIGGER trg_identite_affichage BEFORE INSERT OR UPDATE ON public.step_interactions FOR EACH ROW EXECUTE FUNCTION identite_affichage_canonique();
CREATE TRIGGER trg_propager_identite AFTER UPDATE OF username, avatar_url, emoji ON public.profiles FOR EACH ROW WHEN (((old.username IS DISTINCT FROM new.username) OR (old.avatar_url IS DISTINCT FROM new.avatar_url) OR (old.emoji IS DISTINCT FROM new.emoji))) EXECUTE FUNCTION propager_identite_affichage();
CREATE TRIGGER trg_user_state_horodatage BEFORE INSERT OR UPDATE ON public.user_state FOR EACH ROW EXECUTE FUNCTION user_state_horodatage_serveur();
CREATE TRIGGER trg_user_safety_majorite BEFORE UPDATE ON public.user_safety FOR EACH ROW EXECUTE FUNCTION user_safety_majorite_non_avancable();

-- ===== POLICIES RÉELLES (pg_policies, 2026-09-08, 119 public + 4 storage) =====
CREATE POLICY "analytics_insert_own" ON public.analytics_events AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "blocks_delete_own" ON public.blocks AS PERMISSIVE FOR DELETE TO public USING ((blocker_id = (auth.uid())::text));
CREATE POLICY "blocks_insert_own" ON public.blocks AS PERMISSIVE FOR INSERT TO public WITH CHECK ((blocker_id = (auth.uid())::text));
CREATE POLICY "blocks_select_own" ON public.blocks AS PERMISSIVE FOR SELECT TO public USING ((blocker_id = (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "cdv_collab_delete" ON public.cdv_live_collaborators AS PERMISSIVE FOR DELETE TO public USING (((user_id = (auth.uid())::text) OR (EXISTS ( SELECT 1 FROM cdv_lives l WHERE ((l.id = cdv_live_collaborators.live_id) AND (l.author_id = (auth.uid())::text))))));
CREATE POLICY "cdv_collab_insert_owner" ON public.cdv_live_collaborators AS PERMISSIVE FOR INSERT TO public WITH CHECK (((added_by = (auth.uid())::text) AND (EXISTS ( SELECT 1 FROM cdv_lives l WHERE ((l.id = cdv_live_collaborators.live_id) AND (l.author_id = (auth.uid())::text))))));
CREATE POLICY "cdv_collab_select" ON public.cdv_live_collaborators AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "cdv_comments_delete_own" ON public.cdv_live_comments AS PERMISSIVE FOR DELETE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "cdv_comments_insert_own" ON public.cdv_live_comments AS PERMISSIVE FOR INSERT TO public WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "cdv_comments_select" ON public.cdv_live_comments AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "cdv_followers_delete_own" ON public.cdv_live_followers AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "cdv_followers_insert_own" ON public.cdv_live_followers AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "cdv_followers_select" ON public.cdv_live_followers AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "cdv_reactions_delete_own" ON public.cdv_live_reactions AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "cdv_reactions_insert_own" ON public.cdv_live_reactions AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "cdv_reactions_select" ON public.cdv_live_reactions AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "cdv_steps_delete_own" ON public.cdv_live_steps AS PERMISSIVE FOR DELETE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "cdv_steps_insert_own" ON public.cdv_live_steps AS PERMISSIVE FOR INSERT TO public WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "cdv_steps_select" ON public.cdv_live_steps AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "cdv_steps_update_own" ON public.cdv_live_steps AS PERMISSIVE FOR UPDATE TO public USING ((author_id = (auth.uid())::text)) WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "cdv_lives_delete_own" ON public.cdv_lives AS PERMISSIVE FOR DELETE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "cdv_lives_insert_own" ON public.cdv_lives AS PERMISSIVE FOR INSERT TO public WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "cdv_lives_select" ON public.cdv_lives AS PERMISSIVE FOR SELECT TO public USING (((visibility <> 'private'::text) OR (author_id = (( SELECT auth.uid() AS uid))::text)));
CREATE POLICY "cdv_lives_update_own" ON public.cdv_lives AS PERMISSIVE FOR UPDATE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "Insert erreurs" ON public.client_errors AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Lecture selon visibilite de la cible" ON public.comment_interactions AS PERMISSIVE FOR SELECT TO public USING (((user_id = (( SELECT auth.uid() AS uid))::text) OR comment_target_visible(comment_id)));
CREATE POLICY "ci_delete" ON public.comment_interactions AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "ci_insert" ON public.comment_interactions AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "comment_likes_delete_own" ON public.comment_likes AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "comment_likes_insert_own" ON public.comment_likes AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "comment_likes_select" ON public.comment_likes AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Ecriture propre" ON public.conv_members AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((is_conversation_creator(conv_id) OR ((user_id = (( SELECT auth.uid() AS uid))::text) AND can_join_event_conversation(conv_id))) AND (NOT is_blocked_with(user_id))));
CREATE POLICY "Suppression admin" ON public.conv_members AS PERMISSIVE FOR DELETE TO public USING (((user_id = (auth.uid())::text) OR (EXISTS ( SELECT 1 FROM conversations c WHERE ((c.id = conv_members.conv_id) AND (c.created_by = (auth.uid())::text))))));
CREATE POLICY "Suppression propre" ON public.conv_members AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "conv_members_select_member" ON public.conv_members AS PERMISSIVE FOR SELECT TO public USING (is_conv_member(conv_id, (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "Suppression propre" ON public.conv_messages AS PERMISSIVE FOR DELETE TO public USING ((from_id = (auth.uid())::text));
CREATE POLICY "Update propre" ON public.conv_messages AS PERMISSIVE FOR UPDATE TO public USING ((from_id = (auth.uid())::text));
CREATE POLICY "conv_messages_insert_member" ON public.conv_messages AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (((from_id = (( SELECT auth.uid() AS uid))::text) AND is_conv_member(conv_id, (( SELECT auth.uid() AS uid))::text)));
CREATE POLICY "conv_messages_select_member" ON public.conv_messages AS PERMISSIVE FOR SELECT TO public USING (is_conv_member(conv_id, (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "reads_select" ON public.conv_reads AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "reads_update" ON public.conv_reads AS PERMISSIVE FOR UPDATE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "reads_upsert" ON public.conv_reads AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "conversations_insert_creator" ON public.conversations AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK ((created_by = (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "conversations_select_member" ON public.conversations AS PERMISSIVE FOR SELECT TO public USING (is_conv_member(id, (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "Ecriture propre" ON public.event_attendees AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "Lecture publique" ON public.event_attendees AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Maj de sa propre participation" ON public.event_attendees AS PERMISSIVE FOR UPDATE TO public USING ((user_id = (auth.uid())::text)) WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "Suppression propre" ON public.event_attendees AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "event_comments_delete_own" ON public.event_comments AS PERMISSIVE FOR DELETE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "event_comments_insert_own" ON public.event_comments AS PERMISSIVE FOR INSERT TO public WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "event_comments_select" ON public.event_comments AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "event_reactions_delete" ON public.event_reactions AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "event_reactions_insert" ON public.event_reactions AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "event_reactions_select" ON public.event_reactions AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Ecriture propre" ON public.events AS PERMISSIVE FOR INSERT TO public WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "Lecture publique" ON public.events AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Read events" ON public.events AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Suppression propre" ON public.events AS PERMISSIVE FOR DELETE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "Update organisateurs" ON public.events AS PERMISSIVE FOR UPDATE TO public USING (((author_id = (auth.uid())::text) OR jsonb_exists(co_organizers, (auth.uid())::text)));
CREATE POLICY "Ecriture propre" ON public.follows AS PERMISSIVE FOR INSERT TO public WITH CHECK ((follower_id = (auth.uid())::text));
CREATE POLICY "Lecture publique" ON public.follows AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Read follows" ON public.follows AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Suppression cote suivi" ON public.follows AS PERMISSIVE FOR DELETE TO public USING ((following_id = (auth.uid())::text));
CREATE POLICY "Suppression propre" ON public.follows AS PERMISSIVE FOR DELETE TO public USING ((follower_id = (auth.uid())::text));
CREATE POLICY "Lecture propre" ON public.notifications AS PERMISSIVE FOR SELECT TO public USING ((user_id = (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "Suppression propre" ON public.notifications AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "Update propre" ON public.notifications AS PERMISSIVE FOR UPDATE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "notifications_insert_own_author" ON public.notifications AS PERMISSIVE FOR INSERT TO public WITH CHECK ((from_id = (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "passion_relations_select_all" ON public.passion_relations AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "passion_requests_insert_own" ON public.passion_requests AS PERMISSIVE FOR INSERT TO public WITH CHECK (((user_id = (auth.uid())::text) AND (status = 'pending'::text) AND (resolved_passion_id IS NULL) AND (( SELECT count(*) AS count FROM passion_requests r WHERE ((r.user_id = (auth.uid())::text) AND (r.created_at > (now() - '24:00:00'::interval)))) < 5)));
CREATE POLICY "passion_requests_select_own" ON public.passion_requests AS PERMISSIVE FOR SELECT TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "passions_select_all" ON public.passions AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "post_collab_delete" ON public.post_collaborators AS PERMISSIVE FOR DELETE TO public USING (((user_id = (auth.uid())::text) OR (EXISTS ( SELECT 1 FROM posts p WHERE ((p.id = post_collaborators.post_id) AND (p.author_id = (auth.uid())::text))))));
CREATE POLICY "post_collab_insert_owner" ON public.post_collaborators AS PERMISSIVE FOR INSERT TO public WITH CHECK (((added_by = (auth.uid())::text) AND (EXISTS ( SELECT 1 FROM posts p WHERE ((p.id = post_collaborators.post_id) AND (p.author_id = (auth.uid())::text))))));
CREATE POLICY "post_collab_select" ON public.post_collaborators AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Ecriture propre" ON public.post_comments AS PERMISSIVE FOR INSERT TO public WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "Lecture selon visibilite du post" ON public.post_comments AS PERMISSIVE FOR SELECT TO public USING (((author_id = (( SELECT auth.uid() AS uid))::text) OR post_is_visible(post_id)));
CREATE POLICY "Suppression propre" ON public.post_comments AS PERMISSIVE FOR DELETE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "Update propre" ON public.post_comments AS PERMISSIVE FOR UPDATE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "Ecriture propre" ON public.post_likes AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "Lecture selon visibilite du post" ON public.post_likes AS PERMISSIVE FOR SELECT TO public USING (((user_id = (( SELECT auth.uid() AS uid))::text) OR post_is_visible(post_id)));
CREATE POLICY "Suppression propre" ON public.post_likes AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "Ecriture propre" ON public.posts AS PERMISSIVE FOR INSERT TO public WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "Lecture respectant les comptes prives" ON public.posts AS PERMISSIVE FOR SELECT TO public USING (((author_id = (( SELECT auth.uid() AS uid))::text) OR (NOT (EXISTS ( SELECT 1 FROM profiles pr WHERE ((pr.id = posts.author_id) AND (pr.is_private = true))))) OR (EXISTS ( SELECT 1 FROM follows f WHERE ((f.follower_id = (( SELECT auth.uid() AS uid))::text) AND (f.following_id = posts.author_id))))));
CREATE POLICY "Suppression propre" ON public.posts AS PERMISSIVE FOR DELETE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "Update propre" ON public.posts AS PERMISSIVE FOR UPDATE TO public USING (can_edit_post(id)) WITH CHECK (can_edit_post(id));
CREATE POLICY "Lecture publique" ON public.profiles AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Read profiles" ON public.profiles AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Suppression propre" ON public.profiles AS PERMISSIVE FOR DELETE TO public USING ((id = (auth.uid())::text));
CREATE POLICY "Update propre" ON public.profiles AS PERMISSIVE FOR UPDATE TO public USING ((id = (auth.uid())::text));
CREATE POLICY "Upsert propre" ON public.profiles AS PERMISSIVE FOR INSERT TO public WITH CHECK ((id = (auth.uid())::text));
CREATE POLICY "push_delete_own" ON public.push_subscriptions AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "push_insert_own" ON public.push_subscriptions AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "push_select_own" ON public.push_subscriptions AS PERMISSIVE FOR SELECT TO public USING ((user_id = (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "push_update_own" ON public.push_subscriptions AS PERMISSIVE FOR UPDATE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "reports_insert" ON public.reports AS PERMISSIVE FOR INSERT TO public WITH CHECK ((reporter_id = (auth.uid())::text));
CREATE POLICY "si_delete" ON public.step_interactions AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "si_insert" ON public.step_interactions AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "si_select" ON public.step_interactions AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Ecriture propre" ON public.stories AS PERMISSIVE FOR INSERT TO public WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "Lecture stories respectant les comptes prives" ON public.stories AS PERMISSIVE FOR SELECT TO public USING (((author_id = (( SELECT auth.uid() AS uid))::text) OR (NOT (EXISTS ( SELECT 1 FROM profiles pr WHERE ((pr.id = stories.author_id) AND (pr.is_private = true))))) OR (EXISTS ( SELECT 1 FROM follows f WHERE ((f.follower_id = (( SELECT auth.uid() AS uid))::text) AND (f.following_id = stories.author_id))))));
CREATE POLICY "Suppression propre" ON public.stories AS PERMISSIVE FOR DELETE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "story_views_delete_own" ON public.story_views AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "story_views_insert_own" ON public.story_views AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "story_views_select_own" ON public.story_views AS PERMISSIVE FOR SELECT TO public USING ((user_id = (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "telemetry_insert_own" ON public.telemetry_events AS PERMISSIVE FOR INSERT TO public WITH CHECK (((user_id IS NULL) OR (user_id = (auth.uid())::text)));
CREATE POLICY "user_passions_delete_own" ON public.user_passions AS PERMISSIVE FOR DELETE TO public USING ((user_id = (auth.uid())::text));
CREATE POLICY "user_passions_insert_own" ON public.user_passions AS PERMISSIVE FOR INSERT TO public WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "user_passions_select_all" ON public.user_passions AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "user_passions_update_own" ON public.user_passions AS PERMISSIVE FOR UPDATE TO public USING ((user_id = (auth.uid())::text)) WITH CHECK ((user_id = (auth.uid())::text));
CREATE POLICY "user_safety_select_own" ON public.user_safety AS PERMISSIVE FOR SELECT TO authenticated USING ((user_id = (( SELECT auth.uid() AS uid))::text));
CREATE POLICY "user_state_delete_own" ON public.user_state AS PERMISSIVE FOR DELETE TO public USING (((auth.uid())::text = user_id));
CREATE POLICY "user_state_insert_own" ON public.user_state AS PERMISSIVE FOR INSERT TO public WITH CHECK (((auth.uid())::text = user_id));
CREATE POLICY "user_state_select_own" ON public.user_state AS PERMISSIVE FOR SELECT TO public USING (((( SELECT auth.uid() AS uid))::text = user_id));
CREATE POLICY "user_state_update_own" ON public.user_state AS PERMISSIVE FOR UPDATE TO public USING (((auth.uid())::text = user_id)) WITH CHECK (((auth.uid())::text = user_id));
CREATE POLICY "video_lives_delete" ON public.video_lives AS PERMISSIVE FOR DELETE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "video_lives_insert" ON public.video_lives AS PERMISSIVE FOR INSERT TO public WITH CHECK ((author_id = (auth.uid())::text));
CREATE POLICY "video_lives_select" ON public.video_lives AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "video_lives_update" ON public.video_lives AS PERMISSIVE FOR UPDATE TO public USING ((author_id = (auth.uid())::text));
CREATE POLICY "passio_media_delete" ON storage.objects AS PERMISSIVE FOR DELETE TO public USING (((bucket_id = ANY (ARRAY['content'::text, 'attachments'::text])) AND (owner = auth.uid())));
CREATE POLICY "passio_media_insert_cloisonne" ON storage.objects AS PERMISSIVE FOR INSERT TO public WITH CHECK (storage_chemin_autorise(bucket_id, name));
CREATE POLICY "passio_media_read" ON storage.objects AS PERMISSIVE FOR SELECT TO public USING ((bucket_id = ANY (ARRAY['content'::text, 'attachments'::text])));
CREATE POLICY "passio_media_update_cloisonne" ON storage.objects AS PERMISSIVE FOR UPDATE TO public USING (((bucket_id = ANY (ARRAY['content'::text, 'attachments'::text])) AND (owner = ( SELECT auth.uid() AS uid)))) WITH CHECK (storage_chemin_autorise(bucket_id, name));