
INSERT INTO passions(id,label) VALUES ('musique','Musique'),('velo','Vélo');
INSERT INTO passion_relations VALUES ('musique','velo','related',1,now());
INSERT INTO profiles(id,username,bio,is_private,rs_links) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','alice','bio A',false,'{"ig":"a"}'),('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','bob','bio B',false,null),('cccccccc-cccc-4ccc-8ccc-cccccccccccc','carla','bio C PRIVEE',true,null),('dddddddd-dddd-4ddd-8ddd-dddddddddddd','dan','bio D',false,null);
INSERT INTO posts(id,author_id,content) VALUES ('post_A','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','post de A'),('post_C','cccccccc-cccc-4ccc-8ccc-cccccccccccc','post PRIVE de C');
INSERT INTO stories(id,author_id,content) VALUES ('story_A','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','story A'),('story_C','cccccccc-cccc-4ccc-8ccc-cccccccccccc','story C');
INSERT INTO post_comments(id,post_id,author_id,content) VALUES ('pc_A','post_A','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','c'),('pc_C','post_C','cccccccc-cccc-4ccc-8ccc-cccccccccccc','c');
INSERT INTO post_likes VALUES ('post_A','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),('post_C','cccccccc-cccc-4ccc-8ccc-cccccccccccc');
INSERT INTO comment_interactions(id,comment_id,post_id,user_id,kind,payload) VALUES ('ci_A','pc_A','post_A','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','like',null),('ci_C','pc_C','post_C','cccccccc-cccc-4ccc-8ccc-cccccccccccc','like',null);
INSERT INTO comment_likes VALUES ('pc_A','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',now());
INSERT INTO events(id,author_id,title,address,contact,lat,lng,conv_id) VALUES ('ev1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Sortie','12 rue Exacte, Annecy','0600000000',45.9,6.1,'evgrp_ev1');
INSERT INTO event_attendees(event_id,user_id,rsvp) VALUES ('ev1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','going'),('ev1','cccccccc-cccc-4ccc-8ccc-cccccccccccc','going');
INSERT INTO event_comments(id,event_id,author_id,text) VALUES ('ec1','ev1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','x');
INSERT INTO event_reactions VALUES ('ev1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','🔥',now());
INSERT INTO conversations(id,created_by) VALUES ('conv1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),('evgrp_ev1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
INSERT INTO conv_members VALUES ('conv1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),('conv1','cccccccc-cccc-4ccc-8ccc-cccccccccccc'),('evgrp_ev1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
INSERT INTO conv_messages(id,conv_id,from_id,content) VALUES ('m1','conv1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','message PRIVE A->C');
INSERT INTO conv_reads VALUES ('conv1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',now()),('conv1','cccccccc-cccc-4ccc-8ccc-cccccccccccc',now());
INSERT INTO notifications(id,user_id,kind,from_id,content) VALUES ('n1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','like','cccccccc-cccc-4ccc-8ccc-cccccccccccc','notif de A');
INSERT INTO follows VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','cccccccc-cccc-4ccc-8ccc-cccccccccccc');
INSERT INTO blocks(blocker_id,blocked_id) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','dddddddd-dddd-4ddd-8ddd-dddddddddddd');
INSERT INTO user_state(user_id,data) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','{"secret":1}');
INSERT INTO user_safety(user_id,majority_at) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','2000-01-01');
INSERT INTO push_subscriptions VALUES ('https://push/A','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','{"keys":"x"}',now());
INSERT INTO story_views VALUES ('story_A','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',now());
INSERT INTO user_passions(user_id,passion_id) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','musique');
INSERT INTO passion_requests(user_id,label,normalized_label) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Tricot','tricot');
INSERT INTO telemetry_events(type,user_id,user_label,device_id) VALUES ('action','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','alice','dev-A');
INSERT INTO analytics_events(user_id,event) VALUES ('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','open');
INSERT INTO client_errors(message,uid) VALUES ('err','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
INSERT INTO reports(id,reporter_id,target_type,target_id,reason) VALUES ('r1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','post','post_C','abus');
INSERT INTO step_interactions(id,thread_id,user_id,kind,content) VALUES ('si1','th1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','comment','x');
INSERT INTO video_lives(id,author_id,title) VALUES ('vl1','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','live');
INSERT INTO cdv_lives(id,author_id,destination,visibility) VALUES ('cdv_pub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Rome','public'),('cdv_priv','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Oslo','private');
INSERT INTO cdv_live_steps(id,live_id,author_id,city) VALUES ('st1','cdv_priv','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Oslo');
INSERT INTO cdv_live_comments(id,live_id,author_id,text) VALUES ('cc1','cdv_priv','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','x');
INSERT INTO cdv_live_reactions(id,live_id,user_id,emoji) VALUES ('cr1','cdv_priv','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','x');
INSERT INTO cdv_live_followers VALUES ('cdv_priv','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',now());
INSERT INTO cdv_live_collaborators VALUES ('cdv_priv','dddddddd-dddd-4ddd-8ddd-dddddddddddd','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',now());
INSERT INTO post_collaborators VALUES ('post_A','dddddddd-dddd-4ddd-8ddd-dddddddddddd','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',now());
INSERT INTO storage.objects(bucket_id,name,owner) VALUES ('attachments','conv/conv1/vocal-prive.webm','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),('content','u/aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa/photo.jpg','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
